# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-09-25 11:41-0300\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: api_app/apps.py:303
msgid "Lista de agentes activos de un Grupo"
msgstr "Active agents list for a Group"

#: api_app/apps.py:305
msgid "Campañas relacionadas a un supervisor"
msgstr "Campaigns related to a supervisor"

#: api_app/apps.py:307
msgid "Opciones de calificacion de una campaña (id campaña externo)"
msgstr "Campaign disposition options (external campaign id)"

#: api_app/apps.py:310
msgid "Opciones de calificacion de una campaña (id campaña oml)"
msgstr "Campaign disposition options (OML campaign id)"

#: api_app/apps.py:313
msgid "Ver/editar calificación cliente"
msgstr "View/edit Client Disposition"

#: api_app/apps.py:315
msgid "Crear calificacion cliente"
msgstr "Create Call Disposition"

#: api_app/apps.py:317
msgid "Crear contacto"
msgstr "Create Contact"

#: api_app/apps.py:319
msgid "Metadata de la base de datos de una campaña"
msgstr "Campaign database metadata"

#: api_app/apps.py:321
msgid "Crear nuevo rol"
msgstr "Create new Role"

#: api_app/apps.py:323
msgid "Eliminar rol"
msgstr "Delete Role"

#: api_app/apps.py:325
msgid "Actualizar permisos de Rol"
msgstr "Update Role Permissions"

#: api_app/apps.py:327
msgid "Devuelve información de los agentes en el sistema"
msgstr "Returns Agents information"

#: api_app/apps.py:330
msgid "Reporte de llamadas entrantes de supervisión."
msgstr "Supervision Inbound calls report"

#: api_app/apps.py:332
msgid "Reporte de llamadas salientes no dialer de supervisión."
msgstr "Supervision Outbound non dialer calls report"

#: api_app/apps.py:336
msgid "Ejecuta acciones de supervisión sobre agente (Deslogueo, pausas, etc..)"
msgstr "Apply supervision actions on Agent (Logoff, Pauses, etc..)"

#: api_app/apps.py:339
msgid "Cantidades por tipos de llamada en una campaña"
msgstr "Call types ammount for a Campaign"

#: api_app/apps.py:342
msgid "Cantidades por tipo de calificación en una campaña"
msgstr "Disposition types ammount for a Campaign"

#: api_app/apps.py:345
msgid "Reasignar una Agenda a otro Agente"
msgstr "Reassign Agenda to another Agent"

#: api_app/apps.py:347
msgid "Información de contacto de una  Agenda"
msgstr "Agenda's contact information"

#: api_app/apps.py:349
msgid "Exportar reporte de contactados de una campaña a csv"
msgstr "Export contacted campaign calls report to csv"

#: api_app/apps.py:352
msgid "Exportar reporte de calificados de una campaña a csv"
msgstr "Export dispositioned campaign calls report to csv"

#: api_app/apps.py:355
msgid "Exportar reporte de no atendidos de una campaña a csv"
msgstr "Export unnatended campaign calls report to csv"

#: api_app/apps.py:358 api_app/apps.py:361
msgid "Exportar reporte de calificaciones de una campaña a csv"
msgstr "Export dispositioned campaign calls report to csv"

#: api_app/apps.py:364
msgid "API para exportar resultados de base contactados a csv"
msgstr "API for exporting contacted database results to csv"

#: api_app/apps.py:367
msgid "Contactos de una campaña"
msgstr "Campaign contacts"

#: api_app/apps.py:369
msgid "Ejecuta un click 2 call a una campaña"
msgstr "Start a click 2 call for a campaign"

#: api_app/apps.py:371
msgid "Ejecuta un click 2 call fuera de campaña"
msgstr "Start a click 2 call out of campaign"

#: api_app/apps.py:373
msgid "Ejecuta el login del agente en Asterisk."
msgstr "Agent's Asterisk login"

#: api_app/apps.py:375
msgid "Ejecuta el logout del agente en Asterisk"
msgstr "Agent's Asterisk logout"

#: api_app/apps.py:377
msgid "Logout del agente en OML"
msgstr "Agent's OML logout"

#: api_app/apps.py:379
msgid "Pone al agente en una pausa"
msgstr "Start an Agent's pause"

#: api_app/apps.py:381
msgid "Saca al agente de una pausa"
msgstr "Stop an Agent's pause"

#: api_app/apps.py:383
msgid "Establece el estado Ringing del Agente"
msgstr "Set Agent's Ringing status"

#: api_app/apps.py:385
msgid "Establece el estado Reject del Agente"
msgstr "Save Agent's call reject log"

#: api_app/apps.py:387
msgid "Establece el estado Disabled del Agente"
msgstr "Set Agent's disabled state"

#: api_app/apps.py:389
msgid "Devuelve credenciales SIP de un agente"
msgstr "Return Agent's SIP credentials"

#: api_app/apps.py:391
msgid "Establece el estado de revisión de una Auditoría"
msgstr "Establishes review status for an Audit"

#: api_app/apps.py:394
msgid "Almacena en la base de datos los contactos subidos en archivo csv"
msgstr "Stores uploaded contact of a database in a csv file"

#: api_app/apps.py:397
msgid "Detecta si una llamada esta calificada."
msgstr "Detect if an call is qualified"

#: api_app/apps.py:400
msgid "Reenvía la llave de la instancia registrada por email"
msgstr "Sends registered instance key by email"

#: api_app/apps.py:402
msgid "Retorna el archivo csv de auditoria"
msgstr "Returns audit csv file"

#: api_app/apps.py:405
msgid "Retorna el archivo de grabación especificado"
msgstr "Returns the specified recording file"

#: api_app/apps.py:408
msgid "Retorna Zip con archivos de grabación especificados"
msgstr "Returns .zip file with the specified recording files"

#: api_app/apps.py:411
msgid "Retorna URL del archivos de grabación asociado al callid"
msgstr "Returns the URL of the recording file associated to callid"

#: api_app/apps.py:414
msgid "Devuelve los contactos asignados de una campaña preview"
msgstr "Returns the assigned contacts of a preview campaign"

#: api_app/apps.py:417
msgid "Loggea el evento hold o unhold"
msgstr "Logs a hold or unhold event"

#: api_app/apps.py:420
msgid "Lista de agentes para transferir llamadas"
msgstr "Agents list for call transfers"

#: api_app/apps.py:423
msgid "Lista audios de asterisk"
msgstr "Asterisk audio list"

#: api_app/apps.py:426
msgid "Lista de grupos de agentes"
msgstr "Agent groups list"

#: api_app/apps.py:429
msgid "Lista de Agentes"
msgstr "Agent's list"

#: api_app/apps.py:432
msgid "Dashboard de supervision"
msgstr "Supervision dashboard"

#: api_app/apps.py:435
msgid "Auditoría a supervisores"
msgstr "Supervisor's Audit"

#: api_app/apps.py:438
msgid "Listas de nombres de columnas para Base de datos de Contactos"
msgstr "Contact Database fields names list"

#: api_app/apps.py:441
msgid "Reinicia servicio Wombat Dialer"
msgstr "Restart Wombat Dialer Service"

#: api_app/apps.py:444
msgid "Estado del servicio Wombat Dialer"
msgstr "Wombat Dialer service state"

#: api_app/apps.py:447
msgid "Lista de agentes por campaña"
msgstr "Campaign's agents list"

#: api_app/apps.py:450
msgid "Actualiza los agentes de una campaña"
msgstr "Update a Campaign's agents"

#: api_app/apps.py:453
msgid "Obtiene todos los agentes activos"
msgstr "Get all active agents"

#: api_app/apps.py:456
msgid "Obtiene las pausas que no estan eliminadas"
msgstr "Get non deleted pauses"

#: api_app/apps.py:459
msgid "Lista los conjuntos de pausas"
msgstr "List pause Sets"

#: api_app/apps.py:462
msgid "Obtiene el detalle de un conjunto de pausas"
msgstr "Get pause Set detail"

#: api_app/apps.py:465
msgid "Crea un conjunto de pausas"
msgstr "Create a pause Set"

#: api_app/apps.py:468
msgid "Actualiza un conjunto de pausas"
msgstr "Update pause Set"

#: api_app/apps.py:471
msgid "Elimina un conjunto de pausas"
msgstr "Delete pause Set"

#: api_app/apps.py:474
msgid "Crea una configuracion de pausa"
msgstr "Create pause configuration"

#: api_app/apps.py:477
msgid "Actualiza una configuracion de pausa"
msgstr "Update pause configuration"

#: api_app/apps.py:480
msgid "Elimina una configuracion de pausa"
msgstr "Delete pause configuration"

#: api_app/apps.py:483
msgid "Lista los sitios externos"
msgstr "External Site list"

#: api_app/apps.py:486
msgid "Obtiene el detalle de un sitio externo"
msgstr "Get External Site detail"

#: api_app/apps.py:489
msgid "Crea un sitio externo"
msgstr "Create external site"

#: api_app/apps.py:492
msgid "Actualiza un sitio externo"
msgstr "Update external site"

#: api_app/apps.py:495
msgid "Elimina un sitio externo"
msgstr "Deletes external site"

#: api_app/apps.py:498
msgid "Lista las autenticaciones para sitios externos"
msgstr "External Site authentications list"

#: api_app/apps.py:501
msgid "Obtiene el detalle de una autenticacion para sitio externo"
msgstr "Get External Site Authentication detail"

#: api_app/apps.py:504
msgid "Crea una autenticacion para sitio externo"
msgstr "Create external site authentication"

#: api_app/apps.py:507
msgid "Actualiza una autenticacion para sitio externo"
msgstr "Update external site authentication"

#: api_app/apps.py:510
msgid "Elimina una autenticacion para sitio externo"
msgstr "Deletes external site authentication"

#: api_app/apps.py:513
msgid "Oculta un sitio externo"
msgstr "Hides external site"

#: api_app/apps.py:516
msgid "Desoculta un sitio externo"
msgstr "Unhide external site"

#: api_app/apps.py:519
msgid "Lista las calificaciones"
msgstr "Call Disposition list"

#: api_app/apps.py:522
msgid "Crea una calificacion"
msgstr "Create Call Disposition"

#: api_app/apps.py:525
msgid "Actualiza una calificacion"
msgstr "Update call disposition"

#: api_app/apps.py:528
msgid "Elimina una calificacion"
msgstr "Delete call disposition"

#: api_app/apps.py:531
msgid "Obtiene detalle de una calificacion"
msgstr "Get call disposition detail"

#: api_app/apps.py:534
msgid "Lista los destinos entrantes"
msgstr "Destination list"

#: api_app/apps.py:537
msgid "Lista tipos de destinos entrantes"
msgstr "Destination type list"

#: api_app/apps.py:540
msgid "Lista los sistemas externos"
msgstr "External System list"

#: api_app/apps.py:543
msgid "Crea un sistema externo"
msgstr "Create external system"

#: api_app/apps.py:546
msgid "Actualiza un sistema externo"
msgstr "Update external system"

#: api_app/apps.py:549
msgid "Obtiene detalle de un sistema externo"
msgstr "Get External system detail"

#: api_app/apps.py:552
msgid "Obtiene los agentes para asignar a un sistema externo"
msgstr "Get Agents for External system assignment"

#: api_app/apps.py:555
msgid "Lista los formularios"
msgstr "Call Disposition Forms list"

#: api_app/apps.py:558
msgid "Crea un formulario"
msgstr "Create Call Disposition Form"

#: api_app/apps.py:561
msgid "Actualiza un formulario"
msgstr "Update call disposition form"

#: api_app/apps.py:564
msgid "Obtiene detalle de un formulario"
msgstr "Get call disposition form detail"

#: api_app/apps.py:567
msgid "Elimina un formulario"
msgstr "Delete call disposition"

#: api_app/apps.py:570
msgid "Oculta un formulario"
msgstr "Hides call disposition form"

#: api_app/apps.py:573
msgid "Desoculta un formulario"
msgstr "Unhide call disposition form"

#: api_app/apps.py:576
msgid "Lista las pausas"
msgstr "Pauses list"

#: api_app/apps.py:579
msgid "Crea una pausa"
msgstr "Create a pause"

#: api_app/apps.py:582
msgid "Actualiza una pausa"
msgstr "Update pause"

#: api_app/apps.py:585
msgid "Obtiene detalle de una pausa"
msgstr "Get pause detail"

#: api_app/apps.py:588
msgid "Elimina una pausa"
msgstr "Delete pause"

#: api_app/apps.py:591
msgid "Reactiva una pausa"
msgstr "Reactivate pause"

#: api_app/apps.py:594
msgid "Lista las rutas entrantes"
msgstr "Inbound route list"

#: api_app/apps.py:597
msgid "Crea una ruta entrante"
msgstr "Create Inbound route"

#: api_app/apps.py:600
msgid "Actualiza una ruta entrante"
msgstr "Update Inbound route"

#: api_app/apps.py:603
msgid "Obtiene detalle de una ruta entrante"
msgstr "Get Inbound route detail"

#: api_app/apps.py:606
msgid "Elimina una ruta entrante"
msgstr "Deletes Inbound route"

#: api_app/apps.py:609
msgid "Obtiene los destinos disponibles"
msgstr "Get available destinations list"

#: api_app/apps.py:612
msgid "Lista las rutas salientes"
msgstr "Outbound routes list"

#: api_app/apps.py:615
msgid "Crea una ruta saliente"
msgstr "Create Outbound route"

#: api_app/apps.py:618
msgid "Actualiza una ruta saliente"
msgstr "Update Outbound route"

#: api_app/apps.py:621
msgid "Obtiene detalle de una ruta saliente"
msgstr "Get Outbound route detail"

#: api_app/apps.py:624
msgid "Elimina una ruta saliente"
msgstr "Delete Outbound route"

#: api_app/apps.py:627
msgid "Obtiene las troncales sip para rutas salientes"
msgstr "Get SIP Trunks for Outbound routes"

#: api_app/apps.py:630
msgid "Obtiene las troncales huerfanas de una ruta saliente"
msgstr "Get orphan SIP Trunk for an Outbound route"

#: api_app/apps.py:633
msgid "Reordena las rutas salientes"
msgstr "Rearrange Outbound routes"

#: api_app/apps.py:636
msgid "Lista los grupos horarios"
msgstr "Group of hours list"

#: api_app/apps.py:639
msgid "Crea un grupo horario"
msgstr "Create Group of hours"

#: api_app/apps.py:642
msgid "Actualiza un grupo horario"
msgstr "Update Group of hours"

#: api_app/apps.py:645
msgid "Obtiene detalle de un grupo horario"
msgstr "Get Group of hours detail"

#: api_app/apps.py:648
msgid "Elimina un grupo horario"
msgstr "Delete Group of hours"

#: api_app/apps.py:651
msgid "Lista los ivrs"
msgstr "IVR list"

#: api_app/apps.py:654
msgid "Crea un ivr"
msgstr "Create an IVR"

#: api_app/apps.py:657
msgid "Actualiza un ivr"
msgstr "Update IVR"

#: api_app/apps.py:660
msgid "Obtiene detalle de un ivr"
msgstr "Get IVR detail"

#: api_app/apps.py:663
msgid "Elimina un ivr"
msgstr "Delete IVR"

#: api_app/apps.py:666
msgid "Obtiene los audios disponibles para ivr"
msgstr "Get available audios for IVR"

#: api_app/apps.py:669
msgid "Obtiene los destinos por tipo para un ivr"
msgstr "Get destinations by type for an IVR"

#: api_app/apps.py:672
msgid "Obtener el detalle del registro de la instancia"
msgstr "Get Instance Registration detail"

#: api_app/apps.py:675
msgid "Registrar la instancia"
msgstr "Instance registration"

#: api_app/apps.py:678
msgid "Campañas asociadas a una base de datos de contactos"
msgstr "Campaigns associated to a contact database"

#: api_app/apps.py:681
msgid "Loguea un intento de transferencia a Survey"
msgstr "Logs a transfer to a survey attempt"

#: api_app/forms.py:52 api_app/forms.py:97
#: api_app/tests/tests_api_click2call.py:135
#: api_app/tests/tests_api_click2call.py:207
msgid "El agente no participa en la campaña."
msgstr "The agent is not related to campaign"

#: api_app/forms.py:61 api_app/tests/tests_api_click2call.py:143
msgid "El contacto no corresponde a la campaña."
msgstr "The contact is not related to campaign."

#: api_app/forms.py:99 api_app/tests/tests_api_click2call.py:173
#: api_app/tests/tests_api_click2call.py:195
msgid "El agente no corresponde al sistema externo."
msgstr "The agent is not related to external system."

#: api_app/serializers/register_server.py:40
msgid "No tiene settings de conexion configurados"
msgstr "Missing connection settings configuration"

#: api_app/serializers/register_server.py:44 api_app/views/administrador.py:280
#, python-brace-format
msgid "Error en el intento de conexion a: {0} debido {1}"
msgstr "Error in connection attempt to: {0} due to {1}"

#: api_app/serializers/reportes.py:44
msgid "Addon no instalado"
msgstr "Addon not installed"

#: api_app/serializers/reportes.py:50
msgid "Parámetro requerido"
msgstr "Required parameter"

#: api_app/serializers/reportes.py:56
msgid "No existe una encuesta para esa campaña"
msgstr "A survey does not exist for this campaign"

#: api_app/services/base_datos_contacto_service.py:44
msgid "Ya existe una base de datos de contactos con ese nombre"
msgstr "A contact database with that name already exists"

#: api_app/services/base_datos_contacto_service.py:48
msgid ""
"El archivo especificado para realizar la importación de contactos no es "
"válido."
msgstr "The file specified to import contacts is not valid"

#: api_app/services/base_datos_contacto_service.py:53
#: api_app/tests/tests_api_subir_base_contactos.py:203
#: api_app/views/administrador.py:194
msgid "El archivo a procesar tiene nombres de columnas repetidos."
msgstr "The file to be processed has repeated column names."

#: api_app/services/base_datos_contacto_service.py:127
msgid "Archivo excede máximo de filas permitidas"
msgstr "File exceeds maximum rows allowed"

#: api_app/services/base_datos_contacto_service.py:131
msgid "Error al parsear el archivo csv"
msgstr "Error parsing csv file"

#: api_app/tests/campaign/agents/tests_add_agents_to_campaign.py:89
#: api_app/tests/campaign/agents/tests_add_agents_to_campaign.py:99
#: api_app/views/campaigns/add_agents_to_campaign.py:50
#: api_app/views/campaigns/add_agents_to_campaign.py:201
#: api_app/views/external_system.py:173
msgid "Se obtuvieron los agentes de forma exitosa"
msgstr "Agents fetched successfully"

#: api_app/tests/campaign/agents/tests_add_agents_to_campaign.py:118
#: api_app/views/campaigns/add_agents_to_campaign.py:137
msgid "Se agregaron los agentes de forma exitosa a la campaña"
msgstr "Agents to campaign added successfully"

#: api_app/tests/pause_sets/tests_configuraciones_de_pausas.py:69
#: api_app/views/pause_set.py:232
msgid "Se creo la configuracion de pausa de forma exitosa"
msgstr "Pause configuration created successfully"

#: api_app/tests/pause_sets/tests_configuraciones_de_pausas.py:87
#: api_app/views/pause_set.py:312
msgid "Se actualizo la configuracion de pausa de forma exitosa"
msgstr "Pause configuration updated successfully"

#: api_app/tests/pause_sets/tests_configuraciones_de_pausas.py:105
#: api_app/views/pause_set.py:279
msgid "Se elimino la configuracion de pausa de forma exitosa"
msgstr "Pause configuration deleted successfully"

#: api_app/tests/pause_sets/tests_configuraciones_de_pausas.py:124
#: api_app/views/pause_set.py:239
msgid "El timeout debe ser mayor a cero"
msgstr "Timeout must be greater than zero"

#: api_app/tests/pause_sets/tests_configuraciones_de_pausas.py:136
#: api_app/views/pause_set.py:287
msgid "No puedes dejar a un Conjunto de Pausas vacio"
msgstr "Pause set can't be empty"

#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:66
#: api_app/views/pause_set.py:69
msgid "Se obtuvieron los conjuntos de pausas de forma exitosa"
msgstr "Pause Sets fetched successfully"

#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:88
#: api_app/views/pause_set.py:128
msgid "Se creo el conjunto de pausa de forma exitosa"
msgstr "Pause set created successfully"

#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:109
#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:160
#: api_app/views/pause_set.py:133 api_app/views/pause_set.py:169
msgid "El nombre del conjunto es requerido"
msgstr "Set name required"

#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:125
#: api_app/views/pause_set.py:137
msgid "Debe existir al menos una pausa en el conjunto"
msgstr "Pause Set requires at least une Pause"

#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:143
#: api_app/views/pause_set.py:165
msgid "Se actualizo el conjunto de pausa de forma exitosa"
msgstr "Pause set updated successfully"

#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:172
#: api_app/views/pause_set.py:198
msgid "Se elimino el conjunto de pausa de forma exitosa"
msgstr "Pause set deleted successfully"

#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:186
#: api_app/views/pause_set.py:205
msgid ""
"No puedes borrar un conjunto de pausas que esta asignado a un grupo de "
"agentes"
msgstr "Can't delete pause set already assigned to agent group"

#: api_app/tests/tests_api_call_dispositions.py:57
#: api_app/views/call_disposition.py:43
msgid "Se obtuvieron las calificaciones de forma exitosa"
msgstr "Call disposition fetched successfully"

#: api_app/tests/tests_api_call_dispositions.py:76
#: api_app/views/call_disposition.py:112
msgid "Se creo la calificacion de forma exitosa"
msgstr "Call disposition created successfully"

#: api_app/tests/tests_api_call_dispositions.py:92
#: api_app/views/call_disposition.py:119 api_app/views/call_disposition.py:162
msgid "Error al hacer la peticion"
msgstr "Error making request"

#: api_app/tests/tests_api_call_dispositions.py:112
#: api_app/views/call_disposition.py:154
msgid "Se actualizo la calificacion de forma exitosa"
msgstr "Call disposition updated successfully"

#: api_app/tests/tests_api_call_dispositions.py:128
#: api_app/views/call_disposition.py:192
msgid "Se elimino la calificacion de forma exitosa"
msgstr "Call disposition deleted successfully"

#: api_app/tests/tests_api_click2call.py:104
#: api_app/tests/tests_api_click2call.py:112
#: api_app/tests/tests_api_click2call.py:120
#: api_app/tests/tests_api_click2call.py:165
msgid "Escoja una opción válida. Esa opción no está entre las disponibles."
msgstr "Choose a valid option. That option is not available."

#: api_app/tests/tests_api_click2call.py:157
#: api_app/tests/tests_api_contactos.py:169
#: api_app/tests/tests_api_contactos.py:261 api_app/views/agente.py:224
#: api_app/views/base.py:86 api_app/views/base.py:218
msgid "Sistema externo inexistente."
msgstr "Unkown external system"

#: api_app/tests/tests_api_contactos.py:113 api_app/views/base.py:175
msgid "Contacto agregado"
msgstr "Contact added"

#: api_app/tests/tests_api_contactos.py:141
#: api_app/tests/tests_api_contactos.py:159
#: api_app/tests/tests_api_contactos.py:228
#: api_app/tests/tests_api_contactos.py:251 api_app/views/base.py:117
#: api_app/views/base.py:250
msgid "No tiene permiso para editar la campaña."
msgstr "You don't have permission to edit the campaign"

#: api_app/tests/tests_api_contactos.py:177
#: api_app/tests/tests_api_contactos.py:194
#: api_app/tests/tests_api_contactos.py:271
#: api_app/tests/tests_api_contactos.py:291 api_app/views/base.py:110
#: api_app/views/base.py:243
msgid "Campaña inexistente."
msgstr "Campaign not found"

#: api_app/tests/tests_api_contactos.py:185
#: api_app/tests/tests_api_contactos.py:281 api_app/views/base.py:98
#: api_app/views/base.py:230
msgid "Debe indicar un idCampaign válido."
msgstr "You must provide a valid idCampaign"

#: api_app/tests/tests_api_contactos.py:301
msgid "Ya existe un contacto con ese id externo en la base de datos"
msgstr "A contact with that external id already exist in database"

#: api_app/tests/tests_api_contactos.py:333 api_app/views/base.py:134
msgid "El campo es obligatorio"
msgstr "The field is required"

#: api_app/tests/tests_api_contactos.py:344 api_app/views/base.py:126
msgid "Se recibieron campos incorrectos"
msgstr "Incorrect fields were received"

#: api_app/tests/tests_api_external_site_authentications.py:60
#: api_app/views/external_site_authentication.py:42
msgid "Se obtuvieron las autenticaciones para sitios externos de forma exitosa"
msgstr "External sites authentications fetched successfully"

#: api_app/tests/tests_api_external_site_authentications.py:73
#: api_app/views/external_site_authentication.py:141
msgid ""
"Se obtuvo la informacion de la autenticacion para sitio externo de forma "
"exitosa"
msgstr "External site authentication information fetched successfully "

#: api_app/tests/tests_api_external_site_authentications.py:104
#: api_app/views/external_site_authentication.py:167
msgid "Se elimino la autenticacion para sitio externo de forma exitosa"
msgstr "External site authentication deleted successfully"

#: api_app/tests/tests_api_external_site_authentications.py:120
#: api_app/views/external_site_authentication.py:173
msgid "No está permitido eliminar una autenticacion que tiene sitios externos"
msgstr "Authentications assigned to external sites can not be deleted"

#: api_app/tests/tests_api_external_site_authentications.py:147
#: api_app/views/external_site_authentication.py:69
msgid "Se creo la autenticacion para sitio externo de forma exitosa"
msgstr "External sites created successfully"

#: api_app/tests/tests_api_external_sites.py:66
#: api_app/views/external_site.py:43
msgid "Se obtuvieron los sitios externos de forma exitosa"
msgstr "External sites fetched successfully"

#: api_app/tests/tests_api_external_sites.py:79
#: api_app/views/external_site.py:140
msgid "Se obtuvo la informacion del sitio externo de forma exitosa"
msgstr "External site information fetched successfully "

#: api_app/tests/tests_api_external_sites.py:108
#: api_app/views/external_site.py:165
msgid "Se elimino el sitio externo de forma exitosa"
msgstr "External site deleted successfully"

#: api_app/tests/tests_api_external_sites.py:124
#: api_app/views/external_site.py:171
msgid "No está permitido eliminar un sitio externo asociado a una campaña"
msgstr "External sites assigned to campaigns can not be deleted"

#: api_app/tests/tests_api_external_sites.py:140
#: api_app/views/external_site.py:199
msgid "Se oculto el sitio externo de forma exitosa"
msgstr "External site hidden successfully"

#: api_app/tests/tests_api_external_sites.py:156
#: api_app/views/external_site.py:222
msgid "Se desoculto el sitio externo de forma exitosa"
msgstr "External sites successfully unhidden"

#: api_app/tests/tests_api_external_sites.py:181
#: api_app/views/external_site.py:70
msgid "Se creo el sitio externo de forma exitosa"
msgstr "External sites created successfully"

#: api_app/tests/tests_api_external_systems.py:58
#: api_app/views/external_system.py:44
msgid "Se obtuvieron los sistemas externos de forma exitosa"
msgstr "External systems fetched successfully"

#: api_app/tests/tests_api_external_systems.py:76
#: api_app/views/external_system.py:142
msgid "Se obtuvo la informacion del sistema externo de forma exitosa"
msgstr "External system information fetched successfully "

#: api_app/tests/tests_api_external_systems.py:105
#: api_app/views/external_system.py:72
msgid "Se creo el sistema externo de forma exitosa"
msgstr "External system created successfully"

#: api_app/tests/tests_api_external_systems.py:136
#: api_app/views/external_system.py:103
msgid "Se actualizo el sistema externo de forma exitosa"
msgstr "External system updated successfully"

#: api_app/tests/tests_api_forms.py:109 api_app/views/form.py:43
msgid "Se obtuvieron los formularios de forma exitosa"
msgstr "Call disposition form fetched successfully"

#: api_app/tests/tests_api_forms.py:130 api_app/views/form.py:146
msgid "Se obtuvo la informacion del formulario de forma exitosa"
msgstr "Call disposition form information fetched successfully "

#: api_app/tests/tests_api_forms.py:146 api_app/views/form.py:70
msgid "Se creo el formulario de forma exitosa"
msgstr "Call disposition form created successfully"

#: api_app/tests/tests_api_forms.py:162 api_app/views/form.py:177
msgid "Se elimino el formulario de forma exitosa"
msgstr "Call disposition form deleted successfully"

#: api_app/tests/tests_api_forms.py:176 api_app/views/form.py:183
msgid "No está permitido eliminar un formulario con calificaciones"
msgstr "Call dispositions forms with dispositions can not be deleted"

#: api_app/tests/tests_api_forms.py:192 api_app/views/form.py:211
msgid "Se oculto el formulario de forma exitosa"
msgstr "Call dispositions form hidden successfully"

#: api_app/tests/tests_api_forms.py:208 api_app/views/form.py:234
msgid "Se desoculto el formulario de forma exitosa"
msgstr "Call dispositions form successfully unhidden"

#: api_app/tests/tests_api_forms.py:234 api_app/views/form.py:101
msgid "Se actualizo el formulario de forma exitosa"
msgstr "Call disposition form updated successfully"

#: api_app/tests/tests_api_forms.py:256 api_app/views/form.py:107
msgid "No está permitido actualizar un formulario con calificaciones"
msgstr "Call dispositions forms with dispositions can not be updated"

#: api_app/tests/tests_api_group_of_hour.py:79
#: api_app/views/group_of_hour.py:46
msgid "Se obtuvieron los grupos horarios de forma exitosa"
msgstr "Group of hours fetched successfully"

#: api_app/tests/tests_api_group_of_hour.py:97
#: api_app/views/group_of_hour.py:150
msgid "Se obtuvo la informacion el grupo horario de forma exitosa"
msgstr "Group of hours information fetched successfully "

#: api_app/tests/tests_api_group_of_hour.py:116
#: api_app/views/group_of_hour.py:73
msgid "Se creo el grupo horario de forma exitosa"
msgstr "Group of hours created successfully"

#: api_app/tests/tests_api_group_of_hour.py:134
#: api_app/views/group_of_hour.py:180
msgid "Se elimino el grupo horario de forma exitosa"
msgstr "Group of hours deleted successfully"

#: api_app/tests/tests_api_group_of_hour.py:145
#: api_app/views/group_of_hour.py:186
msgid ""
"No está permitido eliminar un grupo horario asociado a Validacion Fecha Hora"
msgstr "Group of hours with associated to Time conditions can not be deleted"

#: api_app/tests/tests_api_group_of_hour.py:188
#: api_app/views/group_of_hour.py:108
msgid "Se actualizo el grupo horario de forma exitosa"
msgstr "Group of hours updated successfully"

#: api_app/tests/tests_api_inbound_route.py:77
#: api_app/tests/tests_api_outbound_route.py:114
#: api_app/views/inbound_route.py:46 api_app/views/outbound_route.py:49
msgid "Se obtuvieron las rutas entrantes de forma exitosa"
msgstr "Inbound Routes fetched successfully"

#: api_app/tests/tests_api_inbound_route.py:104
#: api_app/views/inbound_route.py:151
msgid "Se obtuvo la informacion de la ruta entrante de forma exitosa"
msgstr "Inbound Route information fetched successfully "

#: api_app/tests/tests_api_inbound_route.py:127
#: api_app/views/inbound_route.py:73
msgid "Se creo la ruta entrante de forma exitosa"
msgstr "Inbound Route created successfully"

#: api_app/tests/tests_api_inbound_route.py:146
#: api_app/views/inbound_route.py:182
msgid "Se elimino la ruta entrante de forma exitosa"
msgstr "Inbound Route deleted successfully"

#: api_app/tests/tests_api_inbound_route.py:192
#: api_app/views/inbound_route.py:107
msgid "Se actualizo la ruta entrante de forma exitosa"
msgstr "Inbound Route updated successfully"

#: api_app/tests/tests_api_ivr.py:219 api_app/views/ivr.py:54
msgid "Se obtuvieron los IVRs de forma exitosa"
msgstr "IVRs fetched successfully"

#: api_app/tests/tests_api_ivr.py:237 api_app/views/ivr.py:165
msgid "Se obtuvo la informacion del IVR de forma exitosa"
msgstr "IVR information fetched successfully "

#: api_app/tests/tests_api_ivr.py:257 api_app/views/ivr.py:82
msgid "Se creo el IVR de forma exitosa"
msgstr "IVR created successfully"

#: api_app/tests/tests_api_ivr.py:290 api_app/views/ivr.py:208
msgid "Se elimino el IVR de forma exitosa"
msgstr "IVR deleted successfully"

#: api_app/tests/tests_api_ivr.py:302 api_app/tests/tests_api_ivr.py:322
#: api_app/views/ivr.py:194
msgid "No se puede eliminar un objeto que es destino en un flujo de llamada."
msgstr "Can not delete an object that is a destination in a call flow."

#: api_app/tests/tests_api_outbound_route.py:138
#: api_app/views/outbound_route.py:152
msgid "Se obtuvo la informacion de la ruta saliente de forma exitosa"
msgstr "Outbound Route information fetched successfully "

#: api_app/tests/tests_api_outbound_route.py:160
#: api_app/views/outbound_route.py:76
msgid "Se creo la ruta saliente de forma exitosa"
msgstr "Outbound Route created successfully"

#: api_app/tests/tests_api_outbound_route.py:181
#: api_app/views/outbound_route.py:184
msgid "Se elimino la ruta saliente de forma exitosa"
msgstr "Outbound Route deleted successfully"

#: api_app/tests/tests_api_outbound_route.py:195
#: api_app/views/outbound_route.py:190
msgid "No está permitido eliminar una ruta saliente asociada a una campaña"
msgstr "Outbound Route assigned to campaigns can not be deleted"

#: api_app/tests/tests_api_outbound_route.py:357
#: api_app/views/outbound_route.py:110
msgid "Se actualizo la ruta saliente de forma exitosa"
msgstr "Outbound Route updated successfully"

#: api_app/tests/tests_api_pauses.py:65 api_app/views/pause.py:66
#: api_app/views/pause_set.py:44
msgid "Se obtuvieron las pausas de forma exitosa"
msgstr "Pauses fetched successfully"

#: api_app/tests/tests_api_pauses.py:83 api_app/views/pause.py:276
msgid "Se obtuvo la informacion de la pausa de forma exitosa"
msgstr "Pause information fetched successfully "

#: api_app/tests/tests_api_pauses.py:103 api_app/views/pause.py:92
msgid "Se creo la pausa de forma exitosa"
msgstr "Pause created successfully"

#: api_app/tests/tests_api_pauses.py:124 api_app/views/pause.py:197
msgid "Se elimino la pausa de forma exitosa"
msgstr "Pause deleted successfully"

#: api_app/tests/tests_api_pauses.py:138 api_app/views/pause.py:203
msgid "No está permitido eliminar un pausa con configuraciones creadas"
msgstr "Pauses with configurations can not be deleted"

#: api_app/tests/tests_api_pauses.py:164 api_app/views/pause.py:140
msgid "Se actualizo la pausa de forma exitosa"
msgstr "Pause updated successfully"

#: api_app/tests/tests_api_pauses.py:202 api_app/views/pause.py:240
msgid "Se reactivo la pausa de forma exitosa"
msgstr "Pause reactivated successfully"

#: api_app/tests/tests_api_permisos.py:55 api_app/views/administrador.py:82
msgid "Ya existe un rol con ese nombre"
msgstr "A Role with that name already exists"

#: api_app/tests/tests_api_permisos.py:65 api_app/views/administrador.py:77
msgid "Se esperaba el campo \"name\""
msgstr "Field \"name\" expected"

#: api_app/tests/tests_api_permisos.py:95 api_app/views/administrador.py:107
msgid "Se esperaba el campo \"role_id\" (numérico)"
msgstr "Field \"role_id\" (numeric) expected"

#: api_app/tests/tests_api_permisos.py:102
#: api_app/tests/tests_api_permisos.py:110
#: api_app/tests/tests_api_permisos.py:170 api_app/views/administrador.py:114
#: api_app/views/administrador.py:144
msgid "Id de Rol incorrecto"
msgstr "Wrong Role Id"

#: api_app/tests/tests_api_permisos.py:119
#: api_app/tests/tests_api_permisos.py:128 api_app/views/administrador.py:118
msgid "Se esperaba el campo \"permissions\" (lista)"
msgstr "Field \"permissions\" (list) expected"

#: api_app/tests/tests_api_permisos.py:138 api_app/views/administrador.py:123
msgid "Lista de permisos incorrecta"
msgstr "Wrong permission list"

#: api_app/tests/tests_api_permisos.py:161 api_app/views/administrador.py:149
msgid "No se puede borrar un rol asignado a usuarios."
msgstr "Deleting a Role assigned to a User is forbidden"

#: api_app/tests/tests_api_register_server.py:55
#: api_app/views/register_server.py:42
msgid "Se obtuvo el registro del servidor forma exitosa"
msgstr "Instance registration data fetched successfully"

#: api_app/tests/tests_api_register_server.py:82
#: api_app/views/register_server.py:77
msgid "Se creo el registro al servidor de forma exitosa"
msgstr "Instance registration created successfully"

#: api_app/tests/tests_api_subir_base_contactos.py:100
#: api_app/views/administrador.py:191
msgid "falta parámetro filename en request"
msgstr "Filename parameter missing in request"

#: api_app/tests/tests_api_subir_base_contactos.py:112
#: api_app/tests/tests_api_subir_base_contactos.py:124
#: api_app/views/administrador.py:213
msgid "falta parámetro:"
msgstr "Missing parameter"

#: api_app/tests/tests_api_subir_base_contactos.py:137
#: api_app/views/administrador.py:228
msgid "campo de teléfono no coincide con nombre de columna"
msgstr "Phone field does not match column name"

#: api_app/tests/tests_api_subir_base_contactos.py:150
#: api_app/views/administrador.py:236
msgid "campo de id externo no coincide con nombre de columna"
msgstr "External id field does not match column name"

#: api_app/tests/tests_api_subir_base_contactos.py:162
#: api_app/views/administrador.py:188
msgid "la extensión del archivo no es .CSV"
msgstr "The file extension is not .CSV"

#: api_app/tests/tests_api_subir_base_contactos.py:176
#: api_app/views/administrador.py:184
#, python-brace-format
msgid "La longitud del nombre no debe exceder los {0} caracteres"
msgstr "The length of the name should not exceed {0} characters"

#: api_app/views/administrador.py:201
msgid "no se pudo crear la base de datos de contacto"
msgstr "Contact Database could not be created"

#: api_app/views/administrador.py:225
msgid "lista de campos teléfono vacia"
msgstr "List of fields phone empty"

#: api_app/views/administrador.py:285
msgid "Error en el servidor externo"
msgstr "Error on the external server"

#: api_app/views/agente.py:71
msgid "Error al generar sip password"
msgstr "Error creating sip password"

#: api_app/views/agente.py:223 api_app/views/agente.py:258
#: api_app/views/base.py:75 api_app/views/base.py:207
msgid "Hubo errores en los datos recibidos"
msgstr "There were errors on received data"

#: api_app/views/agente.py:249
msgid "Error al ejecutar la llamada"
msgstr "Error when executing the call"

#: api_app/views/agente.py:279
msgid "Usted no tiene permiso para realizar esta acción"
msgstr "You don't have permission to perform this action"

#: api_app/views/agente.py:292
msgid "Valor de destination inválido"
msgstr "Invalid destination value"

#: api_app/views/agente.py:302
msgid "Valor de destination_type inválido"
msgstr "Invalid destination_type value"

#: api_app/views/agente.py:306
msgid "Llamada fuera de campaña iniciada"
msgstr "Out of campaign call started"

#: api_app/views/agente.py:503
msgid "Auditoría inexistente"
msgstr "Audit not found"

#: api_app/views/agente.py:508
msgid "No tiene permiso para modificar la auditoría"
msgstr "You don't have permission to edit the audit"

#: api_app/views/auditoria.py:80
msgid "Fecha-Hora"
msgstr "Datetime"

#: api_app/views/auditoria.py:81
msgid "Agente"
msgstr "Agent"

#: api_app/views/auditoria.py:82
msgid "Contacto ID"
msgstr "Contact ID"

#: api_app/views/auditoria.py:83
msgid "Telefono"
msgstr "Phone"

#: api_app/views/auditoria.py:84
msgid "Status"
msgstr "Status"

#: api_app/views/auditoria.py:86
msgid "Calificado"
msgstr "Dispositioned"

#: api_app/views/auditoria.py:87
msgid "Observaciones"
msgstr "Observations"

#: api_app/views/auditoria.py:102
msgid "Pendiente"
msgstr "Pending"

#: api_app/views/auditoria.py:145
msgid "Exportación de auditoria a .csv en proceso"
msgstr "Exportation of audits to a .csv file in process"

#: api_app/views/base_de_contactos.py:42
msgid ""
"Se obtuvieron las campanas asociadas a la base de contactos de forma exitosa"
msgstr "Campaigns associated to contact database fetched successfully"

#: api_app/views/base_de_contactos.py:56
msgid "Error al obtener las campañas asociadas a la base de datos de contactos"
msgstr "Error fetching campaigns associated to Contact Database"

#: api_app/views/call_disposition.py:54
msgid "Error al obtener las calificaciones"
msgstr "Error fetching call dispositions"

#: api_app/views/call_disposition.py:69
msgid "Se obtuvo el detalle de la calificacion de forma exitosa"
msgstr "Call disposition detail fetched successfully"

#: api_app/views/call_disposition.py:79 api_app/views/call_disposition.py:208
msgid "No existe la calificacion"
msgstr "Call disposition does not exist"

#: api_app/views/call_disposition.py:84
msgid "Error al obtener el detalle de la calificacion"
msgstr "Error fetching call disposition detail"

#: api_app/views/call_disposition.py:126
msgid "Error al crear la calificacion"
msgstr "Error creating call disposition"

#: api_app/views/call_disposition.py:170
msgid "No existe la calificacion que se quiere actualizar"
msgstr "call disposition does not exist"

#: api_app/views/call_disposition.py:176
msgid "Error al actualizar la calificacion"
msgstr "Error updating call disposition"

#: api_app/views/call_disposition.py:200
msgid "No está permitido eliminar una calificacion reservada del sistema"
msgstr "System reserved call dispositions can not be deleted"

#: api_app/views/call_disposition.py:213
msgid "Error al eliminar la calificacion"
msgstr "Error deleting call disposition"

#: api_app/views/campaigns/add_agents_to_campaign.py:62
#: api_app/views/supervisor.py:407 api_app/views/supervisor.py:422
msgid "No existe la campaña"
msgstr "Campaign does not exist"

#: api_app/views/campaigns/add_agents_to_campaign.py:82
#, python-brace-format
msgid "QueueAdd failed - agente: {0} de la campana: {1} "
msgstr "QueueAdd failed - agent: {0} from campaign: {1}"

#: api_app/views/campaigns/add_agents_to_campaign.py:111
#, python-brace-format
msgid "QueueRemove failed - agente: {0} de la campana: {1}"
msgstr "QueueRemove failed - agent: {0} from campaign: {1}"

#: api_app/views/campaigns/add_agents_to_campaign.py:122
msgid "No existe el agente en cola"
msgstr "Agent does not exist in queue"

#: api_app/views/campaigns/add_agents_to_campaign.py:144
msgid "No existe la campaña, no se pueden agregar agentes"
msgstr "Campaign does not exist, can't add agents"

#: api_app/views/campaigns/add_agents_to_campaign.py:160
msgid ""
"No existe el agente,                                        no se puede "
"eliminar de la member queue"
msgstr ""
"Agent does not exist,                                            can't "
"delete from member queue"

#: api_app/views/campaigns/add_agents_to_campaign.py:172
msgid ""
"No existe el agente,                                        no se puede "
"crear la member queue"
msgstr ""
"Agent does not exist,                                            can't "
"create member queue"

#: api_app/views/campaigns/add_agents_to_campaign.py:188
msgid "No se pudo confirmar la creación del dialplan"
msgstr "Could not confirm dialplan creation"

#: api_app/views/campaigns/add_agents_to_campaign.py:220
msgid "Error al obtener los agentes activos"
msgstr "Error fetching active agents"

#: api_app/views/external_site.py:53
msgid "Error al obtener los sitios externos"
msgstr "Error fetching external sites"

#: api_app/views/external_site.py:84
msgid "Error al crear el sitio externo"
msgstr "Error creating external site"

#: api_app/views/external_site.py:101
msgid "Se actualizo el sitio externo de forma exitosa"
msgstr "External site updated successfully"

#: api_app/views/external_site.py:118
msgid "No existe el sitio externo que se quiere actualizar"
msgstr "External site does not exist"

#: api_app/views/external_site.py:124
msgid "Error al actualizar el sitio externo"
msgstr "Error updating external site"

#: api_app/views/external_site.py:149
msgid "Error al obtener el detalle del sitio externo"
msgstr "Error fetching external site detail"

#: api_app/views/external_site.py:179
msgid "No existe el sitio externo"
msgstr "External site does not exist"

#: api_app/views/external_site.py:184
msgid "Error al eliminar el sitio externo"
msgstr "Error deleting external site"

#: api_app/views/external_site.py:207
msgid "Error al ocultar el sitio externo"
msgstr "Error hiding external site"

#: api_app/views/external_site.py:230
msgid "Error al desocultar el sitio externo"
msgstr "Error unhiding external site"

#: api_app/views/external_site_authentication.py:52
msgid "Error al obtener las autenticaciones para sitios externos"
msgstr "Error fetching external sites authentication"

#: api_app/views/external_site_authentication.py:84
msgid "Error al crear la autenticacion para sitio externo"
msgstr "Error creating external site authentication"

#: api_app/views/external_site_authentication.py:101
msgid "Se actualizo la autenticacion para sitio externo de forma exitosa"
msgstr "External site authentication updated successfully"

#: api_app/views/external_site_authentication.py:119
msgid "No existe la autenticacion para sitio externo que se quiere actualizar"
msgstr "External site authentication does not exist"

#: api_app/views/external_site_authentication.py:125
msgid "Error al actualizar la autenticacion para sitio externo"
msgstr "Error updating external site authentication"

#: api_app/views/external_site_authentication.py:151
msgid "Error al obtener el detalle de la autenticacion para sitio externo"
msgstr "Error fetching external site authentication detail"

#: api_app/views/external_site_authentication.py:181
msgid "No existe la autenticacion para sitio externo"
msgstr "External site authentication does not exist"

#: api_app/views/external_site_authentication.py:186
msgid "Error al eliminar la autenticacion para sitio externo"
msgstr "Error deleting external site authentication"

#: api_app/views/external_system.py:55
msgid "Error al obtener los sistemas externos"
msgstr "Error fetching external systems"

#: api_app/views/external_system.py:86
msgid "Error al crear el sistema externo"
msgstr "Error creating external system"

#: api_app/views/external_system.py:120
msgid "No existe el sistema externo que se quiere actualizar"
msgstr "External system does not exist"

#: api_app/views/external_system.py:126
msgid "Error al actualizar el sistema externo"
msgstr "Error updating external system"

#: api_app/views/external_system.py:151
msgid "No existe el sistema externo para obtener el detalle"
msgstr "External system does not exist"

#: api_app/views/external_system.py:157
msgid "Error al obtener el detalle del sistema externo"
msgstr "Error fetching external system detail"

#: api_app/views/external_system.py:183
msgid "Error al obtener los agentes"
msgstr "Error fetching agents"

#: api_app/views/form.py:53
msgid "Error al obtener los formularios"
msgstr "Error fetching call disposition forms"

#: api_app/views/form.py:84
msgid "Error al crear el formulario"
msgstr "Error creating call disposition form"

#: api_app/views/form.py:124
msgid "No existe el formulario que se quiere actualizar"
msgstr "Call disposition form does not exist"

#: api_app/views/form.py:130
msgid "Error al actualizar el formulario"
msgstr "Error updating call disposition form"

#: api_app/views/form.py:155
msgid "No existe el formulario para obtener el detalle"
msgstr "Call disposition form does not exist"

#: api_app/views/form.py:161
msgid "Error al obtener el detalle del formulario"
msgstr "Error fetching call disposition form detail"

#: api_app/views/form.py:191
msgid "No existe el formulario"
msgstr "Call disposition form does not exist"

#: api_app/views/form.py:196
msgid "Error al eliminar el formulario"
msgstr "Error deleting call disposition form"

#: api_app/views/form.py:219
msgid "Error al ocultar el formulario"
msgstr "Error hiding call disposition form"

#: api_app/views/form.py:242
msgid "Error al desocultar el formulario"
msgstr "Error unhiding call disposition form"

#: api_app/views/grabaciones.py:94
msgid "Exportación de grabaciones Zip en proceso"
msgstr "Exportation of recordings to a .Zip file in process"

#: api_app/views/group_of_hour.py:56
msgid "Error al obtener los grupos horarios"
msgstr "Error fetching Group of hours"

#: api_app/views/group_of_hour.py:79
msgid ""
"Se creo el grupo horario pero no se pudo cargar la configuración telefónica"
msgstr "Group of hours created, but configuration was not loaded properly"

#: api_app/views/group_of_hour.py:91
msgid "Error al crear el grupo horario"
msgstr "Error creating Group of hours"

#: api_app/views/group_of_hour.py:117
msgid ""
"Se actualizo el grupo horario pero no se pudo cargar la configuración "
"telefónica"
msgstr "Group of hours updated, but configuration was not loaded properly"

#: api_app/views/group_of_hour.py:134
msgid "Error al actualizar el grupo horario"
msgstr "Error updating Group of hours"

#: api_app/views/group_of_hour.py:164
msgid "Error al obtener el detalle del grupo horario"
msgstr "Error fetching Group of hours detail"

#: api_app/views/group_of_hour.py:191
msgid ""
"Se elimino el grupo horario pero no se pudo cargar la configuración "
"telefónica"
msgstr "Group of hours deleted, but configuration was not loaded properly"

#: api_app/views/inbound_route.py:56
msgid "Error al obtener las rutas entrantes"
msgstr "Error fetching Inbound routes"

#: api_app/views/inbound_route.py:79
msgid ""
"Se creo la ruta entrante pero no se pudo cargar la configuración telefónica"
msgstr "Inbound route created, but configuration was not loaded properly"

#: api_app/views/inbound_route.py:90
msgid "Error al crear la ruta entrante"
msgstr "Error creating inbound route"

#: api_app/views/inbound_route.py:118 api_app/views/inbound_route.py:195
msgid ""
"Se actualizo la ruta entrante pero no se pudo cargar la configuración "
"telefónica"
msgstr "Inbound route updated, but configuration was not loaded properly"

#: api_app/views/inbound_route.py:129
msgid "No existe la ruta entrante que se quiere actualizar"
msgstr "Inbound Route does not exist"

#: api_app/views/inbound_route.py:135
msgid "Error al actualizar la ruta entrante"
msgstr "Error updating inbound route"

#: api_app/views/inbound_route.py:160
msgid "No existe la ruta entrante para obtener el detalle"
msgstr "Inbound route does not exist"

#: api_app/views/inbound_route.py:166
msgid "Error al obtener el detalle de la ruta entrante"
msgstr "Error fetching inbound route detail"

#: api_app/views/inbound_route.py:189
msgid ""
"No está permitido eliminar una Ruta Entrante asociada con una campaña que "
"tiene una Ruta Saliente."
msgstr "Inbound routes assigned to campaigns can not be deleted"

#: api_app/views/inbound_route.py:201
msgid "No existe la ruta entrante"
msgstr "Inbound route does not exist"

#: api_app/views/inbound_route.py:206
msgid "Error al eliminar la ruta entrante"
msgstr "Error deleting Inbound route"

#: api_app/views/inbound_route.py:221
msgid "Se obtuvo la informacion de los destinos de forma exitosa"
msgstr "Destinations information fetched successfully "

#: api_app/views/inbound_route.py:240
msgid "Error al obtener los destinos de las rutas entrantes"
msgstr "Error fetching Inbound routes destinations"

#: api_app/views/ivr.py:60
msgid "Error al obtener los ivrs"
msgstr "Error fetching IVRs"

#: api_app/views/ivr.py:84
msgid "Se creo el IVR pero no se pudo cargar la configuración telefónica"
msgstr "IVR created, but configuration was not loaded properly"

#: api_app/views/ivr.py:95 api_app/views/ivr.py:137 api_app/views/ivr.py:205
msgid "Error en los datos enviados"
msgstr "There were errors on sent data"

#: api_app/views/ivr.py:101
msgid "Error al crear el IVR"
msgstr "Error creating IVR"

#: api_app/views/ivr.py:124
msgid "Se actualizo el IVR de forma exitosa"
msgstr "IVR updated successfully"

#: api_app/views/ivr.py:126
msgid "Se actualizo el IVR pero no se pudo cargar la configuración telefónica"
msgstr "IVR updated, but configuration was not loaded properly"

#: api_app/views/ivr.py:143 api_app/views/ivr.py:171 api_app/views/ivr.py:222
msgid "No existe el IVR"
msgstr "IVR does not exist"

#: api_app/views/ivr.py:148
msgid "Error al actualizar el IVR"
msgstr "Error updating IVR"

#: api_app/views/ivr.py:176
msgid "Error al obtener el detalle del IVR"
msgstr "Error fetching IVR detail"

#: api_app/views/ivr.py:199
#, python-brace-format
msgid ""
"No se puede eliminar la campaña.Es usada como destino failover de las "
"campañas: {0}"
msgstr ""
"Can't delete campaign. It's being used as a failover destination in "
"campaigns: {0}"

#: api_app/views/ivr.py:210
msgid "Se elimino el IVR pero no se pudo cargar la configuración telefónica"
msgstr "IVR deleted, but configuration was not loaded properly"

#: api_app/views/ivr.py:227
msgid "Error al eliminar el IVR"
msgstr "Error deleting IVR"

#: api_app/views/ivr.py:246
msgid "Se obtuvieron los archivos de audio de forma exitosa"
msgstr "Audio files fetched successfully"

#: api_app/views/ivr.py:252
msgid "Error al obtener los archivos de audio"
msgstr "Error fetching audio files"

#: api_app/views/ivr.py:280
msgid "Se obtuvieron los destinos de forma exitosa"
msgstr "Destinations fetched successfully"

#: api_app/views/ivr.py:286
msgid "Error al obtener los destinos"
msgstr "Error fetching destinations"

#: api_app/views/outbound_route.py:59
msgid "Error al obtener las rutas salientes"
msgstr "Error fetching Outbound routes"

#: api_app/views/outbound_route.py:82
msgid ""
"Se creo la ruta saliente pero no se pudo cargar la configuración telefónica"
msgstr "Outbound route created, but configuration was not loaded properly"

#: api_app/views/outbound_route.py:93
msgid "Error al crear la ruta saliente"
msgstr "Error creating Outbound route"

#: api_app/views/outbound_route.py:119
msgid ""
"Se actualizo la ruta saliente pero no se pudo cargar la configuración "
"telefónica"
msgstr "Outbound route updated, but configuration was not loaded properly"

#: api_app/views/outbound_route.py:130
msgid "No existe la ruta saliente que se quiere actualizar"
msgstr "Outbound route does not exist"

#: api_app/views/outbound_route.py:136
msgid "Error al actualizar la ruta saliente"
msgstr "Error updating Outbound route"

#: api_app/views/outbound_route.py:162
msgid "No existe la ruta saliente para obtener el detalle"
msgstr "Outbound route does not exist"

#: api_app/views/outbound_route.py:168
msgid "Error al obtener el detalle de la ruta saliente"
msgstr "Error fetching Outbound route detail"

#: api_app/views/outbound_route.py:195
msgid "Se elimino la ruta pero no se pudo cargar la configuración telefónica"
msgstr "Outbound route deleted, but configuration was not loaded properly"

#: api_app/views/outbound_route.py:201 api_app/views/outbound_route.py:261
msgid "No existe la ruta saliente"
msgstr "Outbound route does not exist"

#: api_app/views/outbound_route.py:206
msgid "Error al eliminar la ruta saliente"
msgstr "Error deleting Outbound route"

#: api_app/views/outbound_route.py:221
msgid "Se obtuvieron las troncales sip de forma exitosa"
msgstr "SIP Trunks fetched successfully"

#: api_app/views/outbound_route.py:231
msgid "Error al obtener las troncales"
msgstr "Error fetching SIP Trunks"

#: api_app/views/outbound_route.py:246
msgid ""
"Se obtuvieron las troncales huerfanas de la ruta saliente de forma exitosa"
msgstr "Outbound route's Orphan trunks fetched successfully"

#: api_app/views/outbound_route.py:266
msgid "Error al obtener las troncales huerfanas de la ruta saliente"
msgstr "Error fetching Outbound route's Orphan trunks"

#: api_app/views/outbound_route.py:281
msgid "El orden de las rutas salientes se actualizo de forma exitosa"
msgstr "Outbound routes order updated successfully"

#: api_app/views/outbound_route.py:287
msgid "El orden es un campo requerido"
msgstr "Order is a required field"

#: api_app/views/outbound_route.py:292 api_app/views/outbound_route.py:297
msgid "El orden debe ser una lista de numeros enteros"
msgstr "Order must be an integer list"

#: api_app/views/outbound_route.py:302
msgid "El nuevo orden no coincide con la cantidad de rutas saliente"
msgstr "Order does not match the number of outboud routes"

#: api_app/views/outbound_route.py:309
msgid "No puede haber orden repetido en las rutas salientes"
msgstr "Outbound route's order can not repeat'"

#: api_app/views/outbound_route.py:331
msgid "Error al actualizar el orden de las rutas salientes"
msgstr "Error updating Outbound routes order"

#: api_app/views/pause.py:76 api_app/views/pause_set.py:54
msgid "Error al obtener las pausas"
msgstr "Error fetching pauses"

#: api_app/views/pause.py:106 api_app/views/pause.py:157
#: api_app/views/pause.py:214 api_app/views/pause.py:250
msgid "Error al sincronizar la pausa con asterisk"
msgstr "Error sinchronizing pauses with Asterisk"

#: api_app/views/pause.py:123
msgid "Error al crear la pausa"
msgstr "Error creating pauses"

#: api_app/views/pause.py:181
msgid "Error al actualizar la pausa"
msgstr "Error updating pause"

#: api_app/views/pause.py:225
msgid "Error al eliminar la pausa"
msgstr "Error deleting pause"

#: api_app/views/pause.py:261
msgid "Error al reactivar la pausa"
msgstr "Error reactivating pause"

#: api_app/views/pause.py:291
msgid "Error al obtener el detalle de la pausa"
msgstr "Error fetching pause detail"

#: api_app/views/pause_set.py:80
msgid "Error al obtener los conjuntos de pausas"
msgstr "Error fetching pause sets"

#: api_app/views/pause_set.py:95
msgid "Se obtuvo la informacion del conjunto de pausa de forma exitosa"
msgstr "Pause set information fetched successfully "

#: api_app/views/pause_set.py:112
msgid "Error al obtener el detalle del conjunto de pausa"
msgstr "Error fetching pause set detail"

#: api_app/views/pause_set.py:150
msgid "Error al crear el conjunto de pausa"
msgstr "Error creating pause set"

#: api_app/views/pause_set.py:178 api_app/views/pause_set.py:212
#: api_app/views/pause_set.py:254
msgid "No existe el conjunto de pausa"
msgstr "Pause set does not exist"

#: api_app/views/pause_set.py:183
msgid "Error al actualizar el conjunto de pausa"
msgstr "Error updating pause set"

#: api_app/views/pause_set.py:217
msgid "Error al eliminar el conjunto de pausa"
msgstr "Error deleting pause set"

#: api_app/views/pause_set.py:246
msgid "No existe la pausa"
msgstr "Pause does not exist"

#: api_app/views/pause_set.py:264
msgid "Error al crear la configuracion de pausa"
msgstr "Error creating pause configuration"

#: api_app/views/pause_set.py:292 api_app/views/pause_set.py:322
msgid "No existe la configuracion de pausa"
msgstr "Pause configuration does not exist"

#: api_app/views/pause_set.py:297
msgid "Error al eliminar la configuracion de pausa"
msgstr "Error deleting pause configuration"

#: api_app/views/pause_set.py:327
msgid "Error al actualizar la configuracion de pausa"
msgstr "Error updating pause configuration"

#: api_app/views/register_server.py:61
msgid "Error al obtener el registro al servidor"
msgstr "Error fetching instance registration"

#: api_app/views/register_server.py:91
msgid "Falta informacion para completar el registro"
msgstr "Missing information to complete registration"

#: api_app/views/register_server.py:97
msgid "Error al crear el registro al servidor"
msgstr "Error creating instance registration"

#: api_app/views/reportes.py:44
msgid "Se creo el Log de transferencia a Encuesta"
msgstr "Transfer to survey log created successfully"

#: api_app/views/reportes.py:63
msgid "Error al crear el Log de transferencia"
msgstr "Error creating transfer log"

#: api_app/views/supervisor.py:108 api_app/views/supervisor.py:112
#: api_app/views/supervisor.py:115
msgid "Filtro \"type\" inválido"
msgstr "Invalid \"type\" filter"

#: api_app/views/supervisor.py:124
msgid "Filtro \"agent\" inválido"
msgstr "Invalid \"agent\" filter"

#: api_app/views/supervisor.py:128
msgid "Agente inexistente"
msgstr "Agent not found"

#: api_app/views/supervisor.py:139 api_app/views/supervisor.py:144
#: api_app/views/supervisor.py:147
msgid "Filtro \"status\" inválido"
msgstr "Invalid \"status\" filter"

#: api_app/views/supervisor.py:300 api_app/views/supervisor.py:346
msgid "ID Agenda incorrecto"
msgstr "Wrong Agenda Id"

#: api_app/views/supervisor.py:307
msgid "ID Agente incorrecto"
msgstr "Wrong Agent Id"

#: api_app/views/supervisor.py:315 api_app/views/supervisor.py:353
msgid "No tiene permiso para editar esta Agenda"
msgstr "You don't have permission to edit this Agenda"

#: api_app/views/supervisor.py:372
msgid "Recibidas"
msgstr "Received"

#: api_app/views/supervisor.py:373
msgid "Efectuadas"
msgstr "Dialed"

#: api_app/views/supervisor.py:374
msgid "Atendidas"
msgstr "Attended"

#: api_app/views/supervisor.py:375
msgid "Conectadas"
msgstr "Connected"

#: api_app/views/supervisor.py:376
msgid "No Conectadas"
msgstr "Not connected"

#: api_app/views/supervisor.py:377
msgid "Abandonadas"
msgstr "Abandon"

#: api_app/views/supervisor.py:378
msgid "Expiradas"
msgstr "Expired"

#: api_app/views/supervisor.py:379
msgid "Tiempo de Espera de Conexión(prom.)"
msgstr "Waiting time for connection(avg.)"

#: api_app/views/supervisor.py:380
msgid "Tiempo de Espera de Atención(prom.)"
msgstr "Waiting time for attention(avg.)"

#: api_app/views/supervisor.py:381
msgid "Tiempo de Abandono(prom.)"
msgstr "Abandon time(avg.)"

#: api_app/views/supervisor.py:384
msgid "Efectuadas Manuales"
msgstr "Manual dialed calls"

#: api_app/views/supervisor.py:385
msgid "Conectadas Manuales"
msgstr "Manual connected calls"

#: api_app/views/supervisor.py:386
msgid "No Conectadas Manuales"
msgstr "Manual not connected calls"

#: api_app/views/supervisor.py:387
msgid "Tiempo de Espera de Conexión Manuales(prom.)"
msgstr "Manual calls waiting time for connection(avg.)"

#: api_app/views/supervisor.py:513
msgid "Exportación de CSV en proceso"
msgstr "Exportation of CSV file in process"

#: api_app/views/supervisor.py:561
msgid "Exportación de contactados a .csv en proceso"
msgstr "Exportation of contacted calls to a .csv file in process"

#: api_app/views/supervisor.py:608
msgid "Exportación de calificados a .csv en proceso"
msgstr "Exportation of dispositioned calls to a .csv file in process"

#: api_app/views/supervisor.py:655
msgid "Exportación de no atendidos a .csv en proceso"
msgstr "Exportation of not attended calls to a .csv file in process"

#: api_app/views/supervisor.py:667
msgid "Finalizado"
msgstr "Finalized"

#: api_app/views/supervisor.py:669
msgid "Liberado"
msgstr "Liberated"

#: api_app/views/supervisor.py:671
msgid "Reservado"
msgstr "Reserved"

#: api_app/views/supervisor.py:755
msgid "Exportación de calificaciones a .csv en proceso"
msgstr "Exportation of dispositioned campaign calls to a .csv file in process"

#: api_app/views/supervisor.py:800
msgid "Exportación de Formularios de Gestiones a .csv en proceso"
msgstr "Exportation of Disposition Forms to a .csv file in process"

#: api_app/views/wombat_dialer.py:47 api_app/views/wombat_dialer.py:91
msgid "Refrescando. Espere al menos 15 segundos mientras finaliza el proceso."
msgstr "Refreshing. Wait at least 15 seconds while the process ends."

#~ msgid "Archivos permitidos: .wav"
#~ msgstr "Allowd files: .wav"
