# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-09-17 00:15-0300\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: api_app/apps.py:264
msgid "Lista de agentes activos de un Grupo"
msgstr ""

#: api_app/apps.py:266
msgid "Campañas relacionadas a un supervisor"
msgstr ""

#: api_app/apps.py:268
msgid "Opciones de calificacion de una campaña (id campaña externo)"
msgstr ""

#: api_app/apps.py:271
msgid "Opciones de calificacion de una campaña (id campaña oml)"
msgstr ""

#: api_app/apps.py:274
msgid "Ver/editar calificación cliente"
msgstr ""

#: api_app/apps.py:276
msgid "Crear calificacion cliente"
msgstr ""

#: api_app/apps.py:278
msgid "Crear contacto"
msgstr ""

#: api_app/apps.py:280
msgid "Metadata de la base de datos de una campaña"
msgstr ""

#: api_app/apps.py:282
msgid "Crear nuevo rol"
msgstr ""

#: api_app/apps.py:284
msgid "Eliminar rol"
msgstr ""

#: api_app/apps.py:286
msgid "Actualizar permisos de Rol"
msgstr ""

#: api_app/apps.py:288
msgid "Devuelve información de los agentes en el sistema"
msgstr ""

#: api_app/apps.py:291
msgid "Reporte de llamadas entrantes de supervisión."
msgstr ""

#: api_app/apps.py:293
msgid "Reporte de llamadas salientes no dialer de supervisión."
msgstr ""

#: api_app/apps.py:297
msgid "Ejecuta acciones de supervisión sobre agente (Deslogueo, pausas, etc..)"
msgstr ""

#: api_app/apps.py:300
msgid "Cantidades por tipos de llamada en una campaña"
msgstr ""

#: api_app/apps.py:303
msgid "Cantidades por tipo de calificación en una campaña"
msgstr ""

#: api_app/apps.py:306
msgid "Reasignar una Agenda a otro Agente"
msgstr ""

#: api_app/apps.py:308
msgid "Información de contacto de una  Agenda"
msgstr ""

#: api_app/apps.py:310
msgid "Exportar reporte de contactados de una campaña a csv"
msgstr ""

#: api_app/apps.py:313
msgid "Exportar reporte de calificados de una campaña a csv"
msgstr ""

#: api_app/apps.py:316
msgid "Exportar reporte de no atendidos de una campaña a csv"
msgstr ""

#: api_app/apps.py:319 api_app/apps.py:322
msgid "Exportar reporte de calificaciones de una campaña a csv"
msgstr ""

#: api_app/apps.py:325
msgid "API para exportar resultados de base contactados a csv"
msgstr ""

#: api_app/apps.py:328
msgid "Contactos de una campaña"
msgstr ""

#: api_app/apps.py:330
msgid "Ejecuta un click 2 call"
msgstr ""

#: api_app/apps.py:332
msgid "Ejecuta el login del agente en Asterisk."
msgstr ""

#: api_app/apps.py:334
msgid "Ejecuta el logout del agente en Asterisk"
msgstr ""

#: api_app/apps.py:336
msgid "Logout del agente en OML"
msgstr ""

#: api_app/apps.py:338
msgid "Pone al agente en una pausa"
msgstr ""

#: api_app/apps.py:340
msgid "Saca al agente de una pausa"
msgstr ""

#: api_app/apps.py:342
msgid "Establece el estado Ringing del Agente"
msgstr ""

#: api_app/apps.py:344
msgid "Establece el estado Reject del Agente"
msgstr ""

#: api_app/apps.py:346
msgid "Devuelve credenciales SIP de un agente"
msgstr ""

#: api_app/apps.py:348
msgid "Establece el estado de revisión de una Auditoría"
msgstr ""

#: api_app/apps.py:351
msgid "Almacena en la base de datos los contactos subidos en archivo csv"
msgstr ""

#: api_app/apps.py:354
msgid "Detecta si una llamada esta calificada."
msgstr ""

#: api_app/apps.py:357
msgid "Reenvía la llave de la instancia registrada por email"
msgstr ""

#: api_app/apps.py:359
msgid "Retorna el archivo de grabación especificado"
msgstr ""

#: api_app/apps.py:362
msgid "Retorna Zip con archivos de grabación especificados"
msgstr ""

#: api_app/apps.py:365
msgid "Retorna URL del archivos de grabación asociado al callid"
msgstr ""

#: api_app/apps.py:368
msgid "Devuelve los contactos asignados de una campaña preview"
msgstr ""

#: api_app/apps.py:371
msgid "Loggea el evento hold o unhold"
msgstr ""

#: api_app/apps.py:374
msgid "Lista audios de asterisk"
msgstr ""

#: api_app/apps.py:377
msgid "Lista de grupos de agentes"
msgstr ""

#: api_app/apps.py:380
msgid "Lista de Agentes"
msgstr ""

#: api_app/apps.py:383
msgid "Dashboard de supervision"
msgstr ""

#: api_app/apps.py:386
msgid "Auditoría a supervisores"
msgstr ""

#: api_app/apps.py:389
msgid "Listas de nombres de columnas para Base de datos de Contactos"
msgstr ""

#: api_app/apps.py:392
msgid "Reinicia servicio Wombat Dialer"
msgstr ""

#: api_app/apps.py:395
msgid "Estado del servicio Wombat Dialer"
msgstr ""

#: api_app/apps.py:398
msgid "Lista de agentes por campaña"
msgstr ""

#: api_app/apps.py:401
msgid "Actualiza los agentes de una campaña"
msgstr ""

#: api_app/apps.py:404
msgid "Obtiene todos los agentes activos"
msgstr ""

#: api_app/apps.py:407
msgid "Obtiene las pausas que no estan eliminadas"
msgstr ""

#: api_app/apps.py:410
msgid "Lista los conjuntos de pausas"
msgstr ""

#: api_app/apps.py:413
msgid "Obtiene el detalle de un conjunto de pausas"
msgstr ""

#: api_app/apps.py:416
msgid "Crea un conjunto de pausas"
msgstr ""

#: api_app/apps.py:419
msgid "Actualiza un conjunto de pausas"
msgstr ""

#: api_app/apps.py:422
msgid "Elimina un conjunto de pausas"
msgstr ""

#: api_app/apps.py:425
msgid "Crea una configuracion de pausa"
msgstr ""

#: api_app/apps.py:428
msgid "Actualiza una configuracion de pausa"
msgstr ""

#: api_app/apps.py:431
msgid "Elimina una configuracion de pausa"
msgstr ""

#: api_app/apps.py:434
msgid "Lista los sitios externos"
msgstr ""

#: api_app/apps.py:437
msgid "Obtiene el detalle de un sitio externo"
msgstr ""

#: api_app/apps.py:440
msgid "Crea un sitio externo"
msgstr ""

#: api_app/apps.py:443
msgid "Actualiza un sitio externo"
msgstr ""

#: api_app/apps.py:446
msgid "Elimina un sitio externo"
msgstr ""

#: api_app/apps.py:449
msgid "Lista las autenticaciones para sitios externos"
msgstr ""

#: api_app/apps.py:452
msgid "Obtiene el detalle de una autenticacion para sitio externo"
msgstr ""

#: api_app/apps.py:455
msgid "Crea una autenticacion para sitio externo"
msgstr ""

#: api_app/apps.py:458
msgid "Actualiza una autenticacion para sitio externo"
msgstr ""

#: api_app/apps.py:461
msgid "Elimina una autenticacion para sitio externo"
msgstr ""

#: api_app/apps.py:464
msgid "Oculta un sitio externo"
msgstr ""

#: api_app/apps.py:467
msgid "Desoculta un sitio externo"
msgstr ""

#: api_app/apps.py:470
msgid "Lista las calificaciones"
msgstr ""

#: api_app/apps.py:473
msgid "Crea una calificacion"
msgstr ""

#: api_app/apps.py:476
msgid "Actualiza una calificacion"
msgstr ""

#: api_app/apps.py:479
msgid "Elimina una calificacion"
msgstr ""

#: api_app/apps.py:482
msgid "Obtiene detalle de una calificacion"
msgstr ""

#: api_app/apps.py:485
msgid "Lista los destinos entrantes"
msgstr ""

#: api_app/apps.py:488
msgid "Lista tipos de destinos entrantes"
msgstr ""

#: api_app/apps.py:491
msgid "Lista los sistemas externos"
msgstr ""

#: api_app/apps.py:494
msgid "Crea un sistema externo"
msgstr ""

#: api_app/apps.py:497
msgid "Actualiza un sistema externo"
msgstr ""

#: api_app/apps.py:500
msgid "Obtiene detalle de un sistema externo"
msgstr ""

#: api_app/apps.py:503
msgid "Obtiene los agentes para asignar a un sistema externo"
msgstr ""

#: api_app/apps.py:506
msgid "Lista los formularios"
msgstr ""

#: api_app/apps.py:509
msgid "Crea un formulario"
msgstr ""

#: api_app/apps.py:512
msgid "Actualiza un formulario"
msgstr ""

#: api_app/apps.py:515
msgid "Obtiene detalle de un formulario"
msgstr ""

#: api_app/apps.py:518
msgid "Elimina un formulario"
msgstr ""

#: api_app/apps.py:521
msgid "Oculta un formulario"
msgstr ""

#: api_app/apps.py:524
msgid "Desoculta un formulario"
msgstr ""

#: api_app/apps.py:527
msgid "Lista las pausas"
msgstr ""

#: api_app/apps.py:530
msgid "Crea una pausa"
msgstr ""

#: api_app/apps.py:533
msgid "Actualiza una pausa"
msgstr ""

#: api_app/apps.py:536
msgid "Obtiene detalle de una pausa"
msgstr ""

#: api_app/apps.py:539
msgid "Elimina una pausa"
msgstr ""

#: api_app/apps.py:542
msgid "Reactiva una pausa"
msgstr ""

#: api_app/apps.py:545
msgid "Lista las rutas entrantes"
msgstr ""

#: api_app/apps.py:548
msgid "Crea una ruta entrante"
msgstr ""

#: api_app/apps.py:551
msgid "Actualiza una ruta entrante"
msgstr ""

#: api_app/apps.py:554
msgid "Obtiene detalle de una ruta entrante"
msgstr ""

#: api_app/apps.py:557
msgid "Elimina una ruta entrante"
msgstr ""

#: api_app/apps.py:560
msgid "Obtiene los destinos disponibles"
msgstr ""

#: api_app/apps.py:563
msgid "Lista las rutas salientes"
msgstr ""

#: api_app/apps.py:566
msgid "Crea una ruta saliente"
msgstr ""

#: api_app/apps.py:569
msgid "Actualiza una ruta saliente"
msgstr ""

#: api_app/apps.py:572
msgid "Obtiene detalle de una ruta saliente"
msgstr ""

#: api_app/apps.py:575
msgid "Elimina una ruta saliente"
msgstr ""

#: api_app/apps.py:578
msgid "Obtiene las troncales sip para rutas salientes"
msgstr ""

#: api_app/apps.py:581
msgid "Obtiene las troncales huerfanas de una ruta saliente"
msgstr ""

#: api_app/apps.py:584
msgid "Reordena las rutas salientes"
msgstr ""

#: api_app/forms.py:53 api_app/forms.py:98
#: api_app/tests/tests_api_click2call.py:136
#: api_app/tests/tests_api_click2call.py:208
msgid "El agente no participa en la campaña."
msgstr ""

#: api_app/forms.py:62 api_app/tests/tests_api_click2call.py:144
msgid "El contacto no corresponde a la campaña."
msgstr ""

#: api_app/forms.py:100 api_app/tests/tests_api_click2call.py:174
#: api_app/tests/tests_api_click2call.py:196
msgid "El agente no corresponde al sistema externo."
msgstr ""

#: api_app/services/base_datos_contacto_service.py:45
msgid "Ya existe una base de datos de contactos con ese nombre"
msgstr ""

#: api_app/services/base_datos_contacto_service.py:49
msgid ""
"El archivo especificado para realizar la importación de contactos no es "
"válido."
msgstr ""

#: api_app/services/base_datos_contacto_service.py:54
#: api_app/tests/tests_api_subir_base_contactos.py:204
#: api_app/views/administrador.py:195
msgid "El archivo a procesar tiene nombres de columnas repetidos."
msgstr ""

#: api_app/services/base_datos_contacto_service.py:128
msgid "Archivo excede máximo de filas permitidas"
msgstr ""

#: api_app/services/base_datos_contacto_service.py:132
msgid "Error al parsear el archivo csv"
msgstr ""

#: api_app/tests/campaign/agents/tests_add_agents_to_campaign.py:90
#: api_app/tests/campaign/agents/tests_add_agents_to_campaign.py:100
#: api_app/views/campaigns/add_agents_to_campaign.py:55
#: api_app/views/campaigns/add_agents_to_campaign.py:217
#: api_app/views/external_system.py:174
msgid "Se obtuvieron los agentes de forma exitosa"
msgstr ""

#: api_app/tests/campaign/agents/tests_add_agents_to_campaign.py:119
#: api_app/views/campaigns/add_agents_to_campaign.py:147
msgid "Se agregaron los agentes de forma exitosa a la campaña"
msgstr ""

#: api_app/tests/pause_sets/tests_configuraciones_de_pausas.py:70
#: api_app/views/pause_set.py:233
msgid "Se creo la configuracion de pausa de forma exitosa"
msgstr ""

#: api_app/tests/pause_sets/tests_configuraciones_de_pausas.py:88
#: api_app/views/pause_set.py:313
msgid "Se actualizo la configuracion de pausa de forma exitosa"
msgstr ""

#: api_app/tests/pause_sets/tests_configuraciones_de_pausas.py:106
#: api_app/views/pause_set.py:280
msgid "Se elimino la configuracion de pausa de forma exitosa"
msgstr ""

#: api_app/tests/pause_sets/tests_configuraciones_de_pausas.py:125
#: api_app/views/pause_set.py:240
msgid "El timeout debe ser mayor a cero"
msgstr ""

#: api_app/tests/pause_sets/tests_configuraciones_de_pausas.py:137
#: api_app/views/pause_set.py:288
msgid "No puedes dejar a un Conjunto de Pausas vacio"
msgstr ""

#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:67
#: api_app/views/pause_set.py:70
msgid "Se obtuvieron los conjuntos de pausas de forma exitosa"
msgstr ""

#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:89
#: api_app/views/pause_set.py:129
msgid "Se creo el conjunto de pausa de forma exitosa"
msgstr ""

#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:110
#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:161
#: api_app/views/pause_set.py:134 api_app/views/pause_set.py:170
msgid "El nombre del conjunto es requerido"
msgstr ""

#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:126
#: api_app/views/pause_set.py:138
msgid "Debe existir al menos una pausa en el conjunto"
msgstr ""

#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:144
#: api_app/views/pause_set.py:166
msgid "Se actualizo el conjunto de pausa de forma exitosa"
msgstr ""

#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:173
#: api_app/views/pause_set.py:199
msgid "Se elimino el conjunto de pausa de forma exitosa"
msgstr ""

#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:187
#: api_app/views/pause_set.py:206
msgid ""
"No puedes borrar un conjunto de pausas que esta asignado a un grupo de "
"agentes"
msgstr ""

#: api_app/tests/tests_api_call_dispositions.py:58
#: api_app/views/call_disposition.py:44
msgid "Se obtuvieron las calificaciones de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_call_dispositions.py:77
#: api_app/views/call_disposition.py:113
msgid "Se creo la calificacion de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_call_dispositions.py:93
#: api_app/views/call_disposition.py:120 api_app/views/call_disposition.py:163
msgid "Error al hacer la peticion"
msgstr ""

#: api_app/tests/tests_api_call_dispositions.py:113
#: api_app/views/call_disposition.py:155
msgid "Se actualizo la calificacion de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_call_dispositions.py:129
#: api_app/views/call_disposition.py:193
msgid "Se elimino la calificacion de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_click2call.py:105
#: api_app/tests/tests_api_click2call.py:113
#: api_app/tests/tests_api_click2call.py:121
#: api_app/tests/tests_api_click2call.py:166
msgid "Escoja una opción válida. Esa opción no está entre las disponibles."
msgstr ""

#: api_app/tests/tests_api_click2call.py:158
#: api_app/tests/tests_api_contactos.py:170
#: api_app/tests/tests_api_contactos.py:262 api_app/views/agente.py:221
#: api_app/views/base.py:87 api_app/views/base.py:216
msgid "Sistema externo inexistente."
msgstr ""

#: api_app/tests/tests_api_contactos.py:114 api_app/views/base.py:173
msgid "Contacto agregado"
msgstr ""

#: api_app/tests/tests_api_contactos.py:142
#: api_app/tests/tests_api_contactos.py:160
#: api_app/tests/tests_api_contactos.py:229
#: api_app/tests/tests_api_contactos.py:252 api_app/views/base.py:118
#: api_app/views/base.py:248
msgid "No tiene permiso para editar la campaña."
msgstr ""

#: api_app/tests/tests_api_contactos.py:178
#: api_app/tests/tests_api_contactos.py:195
#: api_app/tests/tests_api_contactos.py:272
#: api_app/tests/tests_api_contactos.py:292 api_app/views/base.py:111
#: api_app/views/base.py:241
msgid "Campaña inexistente."
msgstr ""

#: api_app/tests/tests_api_contactos.py:186
#: api_app/tests/tests_api_contactos.py:282 api_app/views/base.py:99
#: api_app/views/base.py:228
msgid "Debe indicar un idCampaign válido."
msgstr ""

#: api_app/tests/tests_api_contactos.py:302
msgid "Ya existe un contacto con ese id externo en la base de datos"
msgstr ""

#: api_app/tests/tests_api_contactos.py:334 api_app/views/base.py:135
msgid "El campo es obligatorio"
msgstr ""

#: api_app/tests/tests_api_contactos.py:345 api_app/views/base.py:127
msgid "Se recibieron campos incorrectos"
msgstr ""

#: api_app/tests/tests_api_external_site_authentications.py:61
#: api_app/views/external_site_authentication.py:43
msgid "Se obtuvieron las autenticaciones para sitios externos de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_external_site_authentications.py:74
#: api_app/views/external_site_authentication.py:142
msgid ""
"Se obtuvo la informacion de la autenticacion para sitio externo de forma "
"exitosa"
msgstr ""

#: api_app/tests/tests_api_external_site_authentications.py:105
#: api_app/views/external_site_authentication.py:168
msgid "Se elimino la autenticacion para sitio externo de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_external_site_authentications.py:121
#: api_app/views/external_site_authentication.py:174
msgid "No está permitido eliminar una autenticacion que tiene sitios externos"
msgstr ""

#: api_app/tests/tests_api_external_site_authentications.py:148
#: api_app/views/external_site_authentication.py:70
msgid "Se creo la autenticacion para sitio externo de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_external_sites.py:67
#: api_app/views/external_site.py:44
msgid "Se obtuvieron los sitios externos de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_external_sites.py:80
#: api_app/views/external_site.py:141
msgid "Se obtuvo la informacion del sitio externo de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_external_sites.py:109
#: api_app/views/external_site.py:166
msgid "Se elimino el sitio externo de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_external_sites.py:125
#: api_app/views/external_site.py:172
msgid "No está permitido eliminar un sitio externo asociado a una campaña"
msgstr ""

#: api_app/tests/tests_api_external_sites.py:141
#: api_app/views/external_site.py:200
msgid "Se oculto el sitio externo de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_external_sites.py:157
#: api_app/views/external_site.py:223
msgid "Se desoculto el sitio externo de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_external_sites.py:182
#: api_app/views/external_site.py:71
msgid "Se creo el sitio externo de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_external_systems.py:59
#: api_app/views/external_system.py:45
msgid "Se obtuvieron los sistemas externos de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_external_systems.py:77
#: api_app/views/external_system.py:143
msgid "Se obtuvo la informacion del sistema externo de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_external_systems.py:106
#: api_app/views/external_system.py:73
msgid "Se creo el sistema externo de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_external_systems.py:137
#: api_app/views/external_system.py:104
msgid "Se actualizo el sistema externo de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_forms.py:110 api_app/views/form.py:44
msgid "Se obtuvieron los formularios de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_forms.py:131 api_app/views/form.py:147
msgid "Se obtuvo la informacion del formulario de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_forms.py:147 api_app/views/form.py:71
msgid "Se creo el formulario de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_forms.py:163 api_app/views/form.py:178
msgid "Se elimino el formulario de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_forms.py:177 api_app/views/form.py:184
msgid "No está permitido eliminar un formulario con calificaciones"
msgstr ""

#: api_app/tests/tests_api_forms.py:193 api_app/views/form.py:212
msgid "Se oculto el formulario de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_forms.py:209 api_app/views/form.py:235
msgid "Se desoculto el formulario de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_forms.py:235 api_app/views/form.py:102
msgid "Se actualizo el formulario de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_forms.py:257 api_app/views/form.py:108
msgid "No está permitido actualizar un formulario con calificaciones"
msgstr ""

#: api_app/tests/tests_api_inbound_route.py:78
#: api_app/tests/tests_api_outbound_route.py:115
#: api_app/views/inbound_route.py:47 api_app/views/outbound_route.py:50
msgid "Se obtuvieron las rutas entrantes de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_inbound_route.py:105
#: api_app/views/inbound_route.py:152
msgid "Se obtuvo la informacion de la ruta entrante de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_inbound_route.py:128
#: api_app/views/inbound_route.py:74
msgid "Se creo la ruta entrante de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_inbound_route.py:150
#: api_app/views/inbound_route.py:183
msgid "Se elimino la ruta entrante de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_inbound_route.py:196
#: api_app/views/inbound_route.py:108
msgid "Se actualizo la ruta entrante de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_outbound_route.py:139
#: api_app/views/outbound_route.py:153
msgid "Se obtuvo la informacion de la ruta saliente de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_outbound_route.py:161
#: api_app/views/outbound_route.py:77
msgid "Se creo la ruta saliente de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_outbound_route.py:184
#: api_app/views/outbound_route.py:185
msgid "Se elimino la ruta saliente de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_outbound_route.py:198
#: api_app/views/outbound_route.py:191
msgid "No está permitido eliminar una ruta saliente asociada a una campaña"
msgstr ""

#: api_app/tests/tests_api_outbound_route.py:360
#: api_app/views/outbound_route.py:111
msgid "Se actualizo la ruta saliente de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_pauses.py:66 api_app/views/pause.py:67
#: api_app/views/pause_set.py:45
msgid "Se obtuvieron las pausas de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_pauses.py:84 api_app/views/pause.py:277
msgid "Se obtuvo la informacion de la pausa de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_pauses.py:104 api_app/views/pause.py:93
msgid "Se creo la pausa de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_pauses.py:125 api_app/views/pause.py:198
msgid "Se elimino la pausa de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_pauses.py:139 api_app/views/pause.py:204
msgid "No está permitido eliminar un pausa con configuraciones creadas"
msgstr ""

#: api_app/tests/tests_api_pauses.py:165 api_app/views/pause.py:141
msgid "Se actualizo la pausa de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_pauses.py:203 api_app/views/pause.py:241
msgid "Se reactivo la pausa de forma exitosa"
msgstr ""

#: api_app/tests/tests_api_permisos.py:56 api_app/views/administrador.py:83
msgid "Ya existe un rol con ese nombre"
msgstr ""

#: api_app/tests/tests_api_permisos.py:66 api_app/views/administrador.py:78
msgid "Se esperaba el campo \"name\""
msgstr ""

#: api_app/tests/tests_api_permisos.py:96 api_app/views/administrador.py:108
msgid "Se esperaba el campo \"role_id\" (numérico)"
msgstr ""

#: api_app/tests/tests_api_permisos.py:103
#: api_app/tests/tests_api_permisos.py:111
#: api_app/tests/tests_api_permisos.py:171 api_app/views/administrador.py:115
#: api_app/views/administrador.py:145
msgid "Id de Rol incorrecto"
msgstr ""

#: api_app/tests/tests_api_permisos.py:120
#: api_app/tests/tests_api_permisos.py:129 api_app/views/administrador.py:119
msgid "Se esperaba el campo \"permissions\" (lista)"
msgstr ""

#: api_app/tests/tests_api_permisos.py:139 api_app/views/administrador.py:124
msgid "Lista de permisos incorrecta"
msgstr ""

#: api_app/tests/tests_api_permisos.py:162 api_app/views/administrador.py:150
msgid "No se puede borrar un rol asignado a usuarios."
msgstr ""

#: api_app/tests/tests_api_subir_base_contactos.py:101
#: api_app/views/administrador.py:192
msgid "falta parámetro filename en request"
msgstr ""

#: api_app/tests/tests_api_subir_base_contactos.py:113
#: api_app/tests/tests_api_subir_base_contactos.py:125
#: api_app/views/administrador.py:214
msgid "falta parámetro:"
msgstr ""

#: api_app/tests/tests_api_subir_base_contactos.py:138
#: api_app/views/administrador.py:229
msgid "campo de teléfono no coincide con nombre de columna"
msgstr ""

#: api_app/tests/tests_api_subir_base_contactos.py:151
#: api_app/views/administrador.py:237
msgid "campo de id externo no coincide con nombre de columna"
msgstr ""

#: api_app/tests/tests_api_subir_base_contactos.py:163
#: api_app/views/administrador.py:189
msgid "la extensión del archivo no es .CSV"
msgstr ""

#: api_app/tests/tests_api_subir_base_contactos.py:177
#: api_app/views/administrador.py:185
#, python-brace-format
msgid "La longitud del nombre no debe exceder los {0} caracteres"
msgstr ""

#: api_app/views/administrador.py:202
msgid "no se pudo crear la base de datos de contacto"
msgstr ""

#: api_app/views/administrador.py:226
msgid "lista de campos teléfono vacia"
msgstr ""

#: api_app/views/administrador.py:281
#, python-brace-format
msgid "Error en el intento de conexion a: {0} debido {1}"
msgstr ""

#: api_app/views/administrador.py:286
msgid "Error en el servidor externo"
msgstr ""

#: api_app/views/agente.py:68
msgid "Error al generar sip password"
msgstr ""

#: api_app/views/agente.py:220 api_app/views/agente.py:255
#: api_app/views/base.py:76 api_app/views/base.py:205
msgid "Hubo errores en los datos recibidos"
msgstr ""

#: api_app/views/agente.py:246
msgid "Error al ejecutar la llamada"
msgstr ""

#: api_app/views/agente.py:436
msgid "Auditoría inexistente"
msgstr ""

#: api_app/views/agente.py:441
msgid "No tiene permiso para modificar la auditoría"
msgstr ""

#: api_app/views/call_disposition.py:55
msgid "Error al obtener las calificaciones"
msgstr ""

#: api_app/views/call_disposition.py:70
msgid "Se obtuvo el detalle de la calificacion de forma exitosa"
msgstr ""

#: api_app/views/call_disposition.py:80 api_app/views/call_disposition.py:209
msgid "No existe la calificacion"
msgstr ""

#: api_app/views/call_disposition.py:85
msgid "Error al obtener el detalle de la calificacion"
msgstr ""

#: api_app/views/call_disposition.py:127
msgid "Error al crear la calificacion"
msgstr ""

#: api_app/views/call_disposition.py:171
msgid "No existe la calificacion que se quiere actualizar"
msgstr ""

#: api_app/views/call_disposition.py:177
msgid "Error al actualizar la calificacion"
msgstr ""

#: api_app/views/call_disposition.py:201
msgid "No está permitido eliminar una calificacion reservada del sistema"
msgstr ""

#: api_app/views/call_disposition.py:214
msgid "Error al eliminar la calificacion"
msgstr ""

#: api_app/views/campaigns/add_agents_to_campaign.py:68
msgid "La campaña no está activa"
msgstr ""

#: api_app/views/campaigns/add_agents_to_campaign.py:72
#: api_app/views/supervisor.py:407 api_app/views/supervisor.py:422
msgid "No existe la campaña"
msgstr ""

#: api_app/views/campaigns/add_agents_to_campaign.py:96
#, python-brace-format
msgid "QueueAdd failed - agente: {0} de la campana: {1} "
msgstr ""

#: api_app/views/campaigns/add_agents_to_campaign.py:121
#, python-brace-format
msgid "QueueRemove failed - agente: {0} de la campana: {1}"
msgstr ""

#: api_app/views/campaigns/add_agents_to_campaign.py:132
msgid "No existe el agente en cola"
msgstr ""

#: api_app/views/campaigns/add_agents_to_campaign.py:154
msgid "No existe la campaña, no se pueden agregar agentes"
msgstr ""

#: api_app/views/campaigns/add_agents_to_campaign.py:171
msgid ""
"No existe el agente,                                            no se puede "
"eliminar de la member queue"
msgstr ""

#: api_app/views/campaigns/add_agents_to_campaign.py:182
msgid ""
"No existe el agente,                                            no se puede "
"crear la member queue"
msgstr ""

#: api_app/views/campaigns/add_agents_to_campaign.py:200
msgid "No se pudo confirmar la creación del dialplan"
msgstr ""

#: api_app/views/campaigns/add_agents_to_campaign.py:204
msgid "La campaña no está activa, no se pueden agregar agentes"
msgstr ""

#: api_app/views/campaigns/add_agents_to_campaign.py:236
msgid "Error al obtener los agentes activos"
msgstr ""

#: api_app/views/external_site.py:54
msgid "Error al obtener los sitios externos"
msgstr ""

#: api_app/views/external_site.py:85
msgid "Error al crear el sitio externo"
msgstr ""

#: api_app/views/external_site.py:102
msgid "Se actualizo el sitio externo de forma exitosa"
msgstr ""

#: api_app/views/external_site.py:119
msgid "No existe el sitio externo que se quiere actualizar"
msgstr ""

#: api_app/views/external_site.py:125
msgid "Error al actualizar el sitio externo"
msgstr ""

#: api_app/views/external_site.py:150
msgid "Error al obtener el detalle del sitio externo"
msgstr ""

#: api_app/views/external_site.py:180
msgid "No existe el sitio externo"
msgstr ""

#: api_app/views/external_site.py:185
msgid "Error al eliminar el sitio externo"
msgstr ""

#: api_app/views/external_site.py:208
msgid "Error al ocultar el sitio externo"
msgstr ""

#: api_app/views/external_site.py:231
msgid "Error al desocultar el sitio externo"
msgstr ""

#: api_app/views/external_site_authentication.py:53
msgid "Error al obtener las autenticaciones para sitios externos"
msgstr ""

#: api_app/views/external_site_authentication.py:85
msgid "Error al crear la autenticacion para sitio externo"
msgstr ""

#: api_app/views/external_site_authentication.py:102
msgid "Se actualizo la autenticacion para sitio externo de forma exitosa"
msgstr ""

#: api_app/views/external_site_authentication.py:120
msgid "No existe la autenticacion para sitio externo que se quiere actualizar"
msgstr ""

#: api_app/views/external_site_authentication.py:126
msgid "Error al actualizar la autenticacion para sitio externo"
msgstr ""

#: api_app/views/external_site_authentication.py:152
msgid "Error al obtener el detalle de la autenticacion para sitio externo"
msgstr ""

#: api_app/views/external_site_authentication.py:182
msgid "No existe la autenticacion para sitio externo"
msgstr ""

#: api_app/views/external_site_authentication.py:187
msgid "Error al eliminar la autenticacion para sitio externo"
msgstr ""

#: api_app/views/external_system.py:56
msgid "Error al obtener los sistemas externos"
msgstr ""

#: api_app/views/external_system.py:87
msgid "Error al crear el sistema externo"
msgstr ""

#: api_app/views/external_system.py:121
msgid "No existe el sistema externo que se quiere actualizar"
msgstr ""

#: api_app/views/external_system.py:127
msgid "Error al actualizar el sistema externo"
msgstr ""

#: api_app/views/external_system.py:152
msgid "No existe el sistema externo para obtener el detalle"
msgstr ""

#: api_app/views/external_system.py:158
msgid "Error al obtener el detalle del sistema externo"
msgstr ""

#: api_app/views/external_system.py:184
msgid "Error al obtener los agentes"
msgstr ""

#: api_app/views/form.py:54
msgid "Error al obtener los formularios"
msgstr ""

#: api_app/views/form.py:85
msgid "Error al crear el formulario"
msgstr ""

#: api_app/views/form.py:125
msgid "No existe el formulario que se quiere actualizar"
msgstr ""

#: api_app/views/form.py:131
msgid "Error al actualizar el formulario"
msgstr ""

#: api_app/views/form.py:156
msgid "No existe el formulario para obtener el detalle"
msgstr ""

#: api_app/views/form.py:162
msgid "Error al obtener el detalle del formulario"
msgstr ""

#: api_app/views/form.py:192
msgid "No existe el formulario"
msgstr ""

#: api_app/views/form.py:197
msgid "Error al eliminar el formulario"
msgstr ""

#: api_app/views/form.py:220
msgid "Error al ocultar el formulario"
msgstr ""

#: api_app/views/form.py:243
msgid "Error al desocultar el formulario"
msgstr ""

#: api_app/views/grabaciones.py:95
msgid "Exportación de grabaciones Zip en proceso"
msgstr ""

#: api_app/views/inbound_route.py:57
msgid "Error al obtener las rutas entrantes"
msgstr ""

#: api_app/views/inbound_route.py:80
msgid ""
"Se creo la ruta entrante pero no se pudo cargar la configuración telefónica"
msgstr ""

#: api_app/views/inbound_route.py:91
msgid "Error al crear la ruta entrante"
msgstr ""

#: api_app/views/inbound_route.py:119 api_app/views/inbound_route.py:196
msgid ""
"Se actualizo la ruta entrante pero no se pudo cargar la configuración "
"telefónica"
msgstr ""

#: api_app/views/inbound_route.py:130
msgid "No existe la ruta entrante que se quiere actualizar"
msgstr ""

#: api_app/views/inbound_route.py:136
msgid "Error al actualizar la ruta entrante"
msgstr ""

#: api_app/views/inbound_route.py:161
msgid "No existe la ruta entrante para obtener el detalle"
msgstr ""

#: api_app/views/inbound_route.py:167
msgid "Error al obtener el detalle de la ruta entrante"
msgstr ""

#: api_app/views/inbound_route.py:190
msgid ""
"No está permitido eliminar una Ruta Entrante asociada con una campaña que "
"tiene una Ruta Saliente."
msgstr ""

#: api_app/views/inbound_route.py:202
msgid "No existe la ruta entrante"
msgstr ""

#: api_app/views/inbound_route.py:207
msgid "Error al eliminar la ruta entrante"
msgstr ""

#: api_app/views/inbound_route.py:222
msgid "Se obtuvo la informacion de los destinos de forma exitosa"
msgstr ""

#: api_app/views/inbound_route.py:241
msgid "Error al obtener los destinos de las rutas entrantes"
msgstr ""

#: api_app/views/outbound_route.py:60
msgid "Error al obtener las rutas salientes"
msgstr ""

#: api_app/views/outbound_route.py:83
msgid ""
"Se creo la ruta saliente pero no se pudo cargar la configuración telefónica"
msgstr ""

#: api_app/views/outbound_route.py:94
msgid "Error al crear la ruta saliente"
msgstr ""

#: api_app/views/outbound_route.py:120
msgid ""
"Se actualizo la ruta saliente pero no se pudo cargar la configuración "
"telefónica"
msgstr ""

#: api_app/views/outbound_route.py:131
msgid "No existe la ruta saliente que se quiere actualizar"
msgstr ""

#: api_app/views/outbound_route.py:137
msgid "Error al actualizar la ruta saliente"
msgstr ""

#: api_app/views/outbound_route.py:163
msgid "No existe la ruta saliente para obtener el detalle"
msgstr ""

#: api_app/views/outbound_route.py:169
msgid "Error al obtener el detalle de la ruta saliente"
msgstr ""

#: api_app/views/outbound_route.py:196
msgid "Se elimino la ruta pero no se pudo cargar la configuración telefónica"
msgstr ""

#: api_app/views/outbound_route.py:202 api_app/views/outbound_route.py:262
msgid "No existe la ruta saliente"
msgstr ""

#: api_app/views/outbound_route.py:207
msgid "Error al eliminar la ruta saliente"
msgstr ""

#: api_app/views/outbound_route.py:222
msgid "Se obtuvieron las troncales sip de forma exitosa"
msgstr ""

#: api_app/views/outbound_route.py:232
msgid "Error al obtener las troncales"
msgstr ""

#: api_app/views/outbound_route.py:247
msgid ""
"Se obtuvieron las troncales huerfanas de la ruta saliente de forma exitosa"
msgstr ""

#: api_app/views/outbound_route.py:267
msgid "Error al obtener las troncales huerfanas de la ruta saliente"
msgstr ""

#: api_app/views/outbound_route.py:282
msgid "El orden de las rutas salientes se actualizo de forma exitosa"
msgstr ""

#: api_app/views/outbound_route.py:288
msgid "El orden es un campo requerido"
msgstr ""

#: api_app/views/outbound_route.py:293 api_app/views/outbound_route.py:298
msgid "El orden debe ser una lista de numeros enteros"
msgstr ""

#: api_app/views/outbound_route.py:303
msgid "El nuevo orden no coincide con la cantidad de rutas saliente"
msgstr ""

#: api_app/views/outbound_route.py:310
msgid "No puede haber orden repetido en las rutas salientes"
msgstr ""

#: api_app/views/outbound_route.py:332
msgid "Error al actualizar el orden de las rutas salientes"
msgstr ""

#: api_app/views/pause.py:77 api_app/views/pause_set.py:55
msgid "Error al obtener las pausas"
msgstr ""

#: api_app/views/pause.py:107 api_app/views/pause.py:158
#: api_app/views/pause.py:215 api_app/views/pause.py:251
msgid "Error al sincronizar la pausa con asterisk"
msgstr ""

#: api_app/views/pause.py:124
msgid "Error al crear la pausa"
msgstr ""

#: api_app/views/pause.py:182
msgid "Error al actualizar la pausa"
msgstr ""

#: api_app/views/pause.py:226
msgid "Error al eliminar la pausa"
msgstr ""

#: api_app/views/pause.py:262
msgid "Error al reactivar la pausa"
msgstr ""

#: api_app/views/pause.py:292
msgid "Error al obtener el detalle de la pausa"
msgstr ""

#: api_app/views/pause_set.py:81
msgid "Error al obtener los conjuntos de pausas"
msgstr ""

#: api_app/views/pause_set.py:96
msgid "Se obtuvo la informacion del conjunto de pausa de forma exitosa"
msgstr ""

#: api_app/views/pause_set.py:113
msgid "Error al obtener el detalle del conjunto de pausa"
msgstr ""

#: api_app/views/pause_set.py:151
msgid "Error al crear el conjunto de pausa"
msgstr ""

#: api_app/views/pause_set.py:179 api_app/views/pause_set.py:213
#: api_app/views/pause_set.py:255
msgid "No existe el conjunto de pausa"
msgstr ""

#: api_app/views/pause_set.py:184
msgid "Error al actualizar el conjunto de pausa"
msgstr ""

#: api_app/views/pause_set.py:218
msgid "Error al eliminar el conjunto de pausa"
msgstr ""

#: api_app/views/pause_set.py:247
msgid "No existe la pausa"
msgstr ""

#: api_app/views/pause_set.py:265
msgid "Error al crear la configuracion de pausa"
msgstr ""

#: api_app/views/pause_set.py:293 api_app/views/pause_set.py:323
msgid "No existe la configuracion de pausa"
msgstr ""

#: api_app/views/pause_set.py:298
msgid "Error al eliminar la configuracion de pausa"
msgstr ""

#: api_app/views/pause_set.py:328
msgid "Error al actualizar la configuracion de pausa"
msgstr ""

#: api_app/views/supervisor.py:108 api_app/views/supervisor.py:112
#: api_app/views/supervisor.py:115
msgid "Filtro \"type\" inválido"
msgstr ""

#: api_app/views/supervisor.py:124
msgid "Filtro \"agent\" inválido"
msgstr ""

#: api_app/views/supervisor.py:128
msgid "Agente inexistente"
msgstr ""

#: api_app/views/supervisor.py:139 api_app/views/supervisor.py:144
#: api_app/views/supervisor.py:147
msgid "Filtro \"status\" inválido"
msgstr ""

#: api_app/views/supervisor.py:300 api_app/views/supervisor.py:346
msgid "ID Agenda incorrecto"
msgstr ""

#: api_app/views/supervisor.py:307
msgid "ID Agente incorrecto"
msgstr ""

#: api_app/views/supervisor.py:315 api_app/views/supervisor.py:353
msgid "No tiene permiso para editar esta Agenda"
msgstr ""

#: api_app/views/supervisor.py:372
msgid "Recibidas"
msgstr ""

#: api_app/views/supervisor.py:373
msgid "Efectuadas"
msgstr ""

#: api_app/views/supervisor.py:374
msgid "Atendidas"
msgstr ""

#: api_app/views/supervisor.py:375
msgid "Conectadas"
msgstr ""

#: api_app/views/supervisor.py:376
msgid "No Conectadas"
msgstr ""

#: api_app/views/supervisor.py:377
msgid "Abandonadas"
msgstr ""

#: api_app/views/supervisor.py:378
msgid "Expiradas"
msgstr ""

#: api_app/views/supervisor.py:379
msgid "Tiempo de Espera de Conexión(prom.)"
msgstr ""

#: api_app/views/supervisor.py:380
msgid "Tiempo de Espera de Atención(prom.)"
msgstr ""

#: api_app/views/supervisor.py:381
msgid "Tiempo de Abandono(prom.)"
msgstr ""

#: api_app/views/supervisor.py:384
msgid "Efectuadas Manuales"
msgstr ""

#: api_app/views/supervisor.py:385
msgid "Conectadas Manuales"
msgstr ""

#: api_app/views/supervisor.py:386
msgid "No Conectadas Manuales"
msgstr ""

#: api_app/views/supervisor.py:387
msgid "Tiempo de Espera de Conexión Manuales(prom.)"
msgstr ""

#: api_app/views/supervisor.py:513
msgid "Exportación de CSV en proceso"
msgstr ""

#: api_app/views/supervisor.py:561
msgid "Exportación de contactados a .csv en proceso"
msgstr ""

#: api_app/views/supervisor.py:608
msgid "Exportación de calificados a .csv en proceso"
msgstr ""

#: api_app/views/supervisor.py:655
msgid "Exportación de no atendidos a .csv en proceso"
msgstr ""

#: api_app/views/supervisor.py:667
msgid "Finalizado"
msgstr ""

#: api_app/views/supervisor.py:669
msgid "Liberado"
msgstr ""

#: api_app/views/supervisor.py:671
msgid "Reservado"
msgstr ""

#: api_app/views/supervisor.py:755
msgid "Exportación de calificaciones a .csv en proceso"
msgstr ""

#: api_app/views/supervisor.py:800
msgid "Exportación de Formularios de Gestiones a .csv en proceso"
msgstr ""

#: api_app/views/wombat_dialer.py:48 api_app/views/wombat_dialer.py:92
msgid "Refrescando. Espere al menos 15 segundos mientras finaliza el proceso."
msgstr ""

#: notification_app/message/apps.py:29
msgid "Lista de los mensajes de correos que el sistema soporta"
msgstr ""

#: notification_app/message/apps.py:33
msgid "Obtiene detalle de un mensaje de correo"
msgstr ""
